In [10]:
import pandas as pd
from pathlib import Path

In [11]:
transients = pd.read_parquet(
    "snia_results.parquet",
    engine="fastparquet",
)

In [12]:
transients

,diaObjectId,tns_name,z,catalogue_object_id,tns_prefix,type,ra,decl,absMag,nDiaSources
0,170019717277810735,2026ctw,0.150000,"10000,342494,11570",SN,SN Ia,151.740293,1.927064,NaN,754
1,170028486191218743,2026qrh,0.100000,"10000,81273,866",SN,SN Ia,64.185342,-48.943229,NaN,88
2,170028500610711681,2024xom,0.044167,CGCG036-024,SN,SN Ia,150.746125,2.336469,NaN,165
3,170028510695916335,2025mbp,0.046160,2MASXJ10062208+0109317,SN,SN Ia,151.592617,1.158385,NaN,273
4,170028520834072659,2026fgl,0.164000,WISEAJ095652.35+032811.7,SN,SN Ia,149.218165,3.469919,-16.5385,19
...,...,...,...,...,...,...,...,...,...,...
122,170661828398940941,2025bbx,0.067000,14470795-3930390,SN,SN Ia,221.785403,-39.509297,NaN,3
123,313893021499785278,2026ezw,0.131000,SDSSJ095832.59+011610.2,SN,SN Ia,149.635687,1.269344,NaN,20
124,313932566867476549,2026qrh,0.100000,"10000,81273,866",SN,SN Ia,64.185342,-48.943229,NaN,9
125,313972182793322538,2026fgl,0.164000,WISEAJ095652.35+032811.7,SN,SN Ia,149.218165,3.469919,-16.2020,17
126,313976545586708672,2026fgl,0.164000,2MASXJ09565234+0328119,SN,SN Ia,149.218165,3.469919,-17.2440,146

In [13]:
transients = (
    transients[["diaObjectId", "tns_name", "ra", "decl"]]
    .rename(columns={"decl": "dec"})
    .dropna()
    .reset_index(drop=True)
    .copy()
)

transients["tns_name"] = transients["tns_name"].astype(str)

print(f"Associating {len(transients)} transients")
display(transients)

Associating 127 transients

            diaObjectId tns_name          ra        dec
0    170019717277810735  2026ctw  151.740293   1.927064
1    170028486191218743  2026qrh   64.185342 -48.943229
2    170028500610711681  2024xom  150.746125   2.336469
3    170028510695916335  2025mbp  151.592617   1.158385
4    170028520834072659  2026fgl  149.218165   3.469919
..                  ...      ...         ...        ...
122  170661828398940941  2025bbx  221.785403 -39.509297
123  313893021499785278  2026ezw  149.635687   1.269344
124  313932566867476549  2026qrh   64.185342 -48.943229
125  313972182793322538  2026fgl  149.218165   3.469919
126  313976545586708672  2026fgl  149.218165   3.469919

[127 rows x 4 columns]

In [14]:
import inspect
import textwrap
import astro_prost.helpers as helpers

func = helpers.build_panstarrs_candidates
source = textwrap.dedent(inspect.getsource(func))
lines = source.splitlines()

for i, line in enumerate(lines):
    if line.lstrip().startswith("temp_mag_r_std[temp_mag_r_std >"):
        indent = line[:len(line) - len(line.lstrip())]
        lines.insert(
            i,
            indent + "temp_mag_r_std = temp_mag_r_std.copy()",
        )
        break
else:
    raise RuntimeError("Could not locate the failing line; no patch applied.")

# Compile the patched function using the same module globals.
namespace = {}
exec(compile("\n".join(lines), "<prost_panstarrs_fix>", "exec"),
     helpers.__dict__, namespace)

# Update the existing function so existing references also use the fix.
func.__code__ = namespace[func.__name__].__code__

print("Applied writable-array fix to PROST's Pan-STARRS function.")

OSError: could not get source code

In [ ]:
import inspect
import textwrap
import traceback

import pandas as pd
import astro_prost.helpers as prost_helpers
from scipy.stats import gamma, uniform
from astro_prost import associate_sample

# Temporary read-only fix without editing helpers.py.
if not getattr(prost_helpers, "_shape_r_copy_patch_applied", False):
    source = textwrap.dedent(
        inspect.getsource(prost_helpers.calc_shape_props_decals)
    )

    old = 'candidate_hosts["shape_r"].values'
    new = 'candidate_hosts["shape_r"].to_numpy(copy=True)'

    if old not in source:
        raise RuntimeError("Expected shape_r code not found.")

    source = source.replace(old, new)
    exec(
        compile(source, "<prost_notebook_patch>", "exec"),
        prost_helpers.__dict__,
    )
    prost_helpers._shape_r_copy_patch_applied = True

# Collect results in memory.
results = []
failed = []

for i in range(len(transients)):
    one_transient = transients.iloc[[i]].copy().reset_index(drop=True)
    name = str(one_transient.iloc[0]["tns_name"])

    try:
        result = associate_sample(
        one_transient,
        catalogs=["decals", "panstarrs", "skymapper"],
        name_col="tns_name",
        coord_cols=("ra", "dec"),
        priors={"offset": uniform(loc=0, scale=10)},
        likes={"offset": gamma(a=0.75)},
        n_samples=1000,  # Match the 1,000 samples used internally.
        parallel=False,
        save=False,
        )
    

        if isinstance(result, Exception):
            raise result

        if not isinstance(result, pd.DataFrame):
            raise TypeError(
                f"Expected DataFrame; got {type(result).__name__}"
            )

        if result.empty:
            raise ValueError("PROST returned an empty DataFrame.")

        results.append(result)
        print(f"{i + 1}/{len(transients)} done: {name}")

    except Exception as exc:
        failed.append({"tns_name": name, "error": repr(exc)})
        print(f"{i + 1}/{len(transients)} failed: {name}: {exc}")
        traceback.print_exc()

hosts = pd.concat(results, ignore_index=True) if results else pd.DataFrame()
failed_df = pd.DataFrame(failed, columns=["tns_name", "error"])

display(hosts)
display(failed_df)

2026-10-14 11:21:43,280- INFO - Conditioning association on the following properties: ['offset']
2026-10-14 11:21:45,934- INFO - Loaded GLADE+ catalog.
2026-10-14 11:21:45,939- INFO -

Associating 2026ctw at RA, DEC = 151.740293, 1.927064 (redshift nan)
2026-10-14 11:21:49,401- INFO - Association successful!
2026-10-14 11:21:49,421- INFO -

Properties of best host (in decals dr9) for 2026ctw:
    objID: 9906622211952776
    R.A. (deg): 151.740166
    Dec. (deg): 1.927030
    Posterior: 1.0000e+00
    Redshift: 0.7213 ± 0.3376 (PHOT)
    Absolute Magnitude: -20.3 ± 1.1 (r)
    Transient Offset: 0.5 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:21:49,422- INFO -

Properties of 2nd best host (in decals dr9) for 2026ctw:
    Redshift: 1.0042 ± 0.1648 (PHOT)
    Absolute Magnitude: -19.8 ± 1.2 (r)
    Transient Offset: 292.4 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:21:49,422- INFO - Chosen galaxy has catalog ID of 9906622211952776 and RA, DEC = 151.740166, 1.927030
2026-10-14 11:21:49,440- INFO - Conditioning association on the following properties: ['offset']

1/127 done: 2026ctw

2026-10-14 11:21:51,505- INFO - Loaded GLADE+ catalog.
2026-10-14 11:21:51,507- INFO -

Associating 2026qrh at RA, DEC = 64.185342, -48.943229 (redshift nan)
2026-10-14 11:21:54,096- INFO - Association successful!
2026-10-14 11:21:54,214- INFO -

Properties of best host (in decals dr9) for 2026qrh:
    objID: 9906605092569380
    R.A. (deg): 64.185370
    Dec. (deg): -48.943233
    Posterior: 9.8785e-01
    Redshift: 0.1125 ± 0.0167 (PHOT)
    Absolute Magnitude: -20.9 ± 0.9 (r)
    Transient Offset: 0.1 ± 0.1 arcsec
    Transient Offset Posterior: 9.8785e-01
2026-10-14 11:21:54,215- INFO -

Properties of 2nd best host (in decals dr9) for 2026qrh:
    Redshift: 1.2030 ± 0.1423 (PHOT)
    Absolute Magnitude: -21.5 ± 1.2 (r)
    Transient Offset: 297.7 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:21:54,215- INFO - Chosen galaxy has catalog ID of 9906605092569380 and RA, DEC = 64.185370, -48.943233
2026-10-14 11:21:54,242- INFO - Conditioning association on the following properties: ['offset']

2/127 done: 2026qrh

2026-10-14 11:21:56,405- INFO - Loaded GLADE+ catalog.
2026-10-14 11:21:56,406- INFO -

Associating 2024xom at RA, DEC = 150.746125, 2.336469 (redshift nan)
2026-10-14 11:21:58,360- INFO - Association successful!
2026-10-14 11:21:58,385- INFO -

Properties of best host (in decals dr9) for 2024xom:
    objID: 9906622306063947
    R.A. (deg): 150.743722
    Dec. (deg): 2.335828
    Posterior: 7.3434e-01
    Redshift: 0.1483 ± 0.0741 (PHOT)
    Absolute Magnitude: -20.1 ± 1.0 (r)
    Transient Offset: 8.9 ± 0.1 arcsec
    Transient Offset Posterior: 7.3434e-01
2026-10-14 11:21:58,386- INFO -

Properties of 2nd best host (in decals dr9) for 2024xom:
    Redshift: 0.7043 ± 0.3117 (PHOT)
    Absolute Magnitude: -19.5 ± 1.2 (r)
    Transient Offset: 299.4 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:21:58,386- INFO - Chosen galaxy has catalog ID of 9906622306063947 and RA, DEC = 150.743722, 2.335828
2026-10-14 11:21:58,400- INFO - Conditioning association on the following properties: ['offset']

3/127 done: 2024xom

2026-10-14 11:22:02,213- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:02,220- INFO -

Associating 2025mbp at RA, DEC = 151.592617, 1.158385 (redshift nan)
2026-10-14 11:22:04,230- INFO - Association successful!
2026-10-14 11:22:04,251- INFO -

Properties of best host (in decals dr9) for 2025mbp:
    objID: 9906621928834589
    R.A. (deg): 151.591936
    Dec. (deg): 1.159004
    Posterior: 1.0000e+00
    Redshift: 0.0462 ± 0.0023 (SPEC)
    Absolute Magnitude: -19.3 ± 0.9 (r)
    Transient Offset: 3.3 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:22:04,252- INFO -

Properties of 2nd best host (in decals dr9) for 2025mbp:
    Redshift: 0.4413 ± 0.1184 (PHOT)
    Absolute Magnitude: -19.1 ± 1.1 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:04,252- INFO - Chosen galaxy has catalog ID of 9906621928834589 and RA, DEC = 151.591936, 1.159004
2026-10-14 11:22:04,304- INFO - Conditioning association on the following properties: ['offset']

4/127 done: 2025mbp

2026-10-14 11:22:07,405- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:07,412- INFO -

Associating 2026fgl at RA, DEC = 149.218165, 3.469919 (redshift nan)
2026-10-14 11:22:10,316- INFO - Association successful!
2026-10-14 11:22:10,347- INFO -

Properties of best host (in decals dr9) for 2026fgl:
    objID: 9906622777393393
    R.A. (deg): 149.218121
    Dec. (deg): 3.469923
    Posterior: 1.0000e+00
    Redshift: 0.1643 ± 0.0082 (SPEC)
    Absolute Magnitude: -22.3 ± 0.9 (r)
    Transient Offset: 0.2 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:22:10,348- INFO -

Properties of 2nd best host (in decals dr9) for 2026fgl:
    Redshift: 0.9634 ± 0.1610 (PHOT)
    Absolute Magnitude: -20.6 ± 1.2 (r)
    Transient Offset: 297.4 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:10,348- INFO - Chosen galaxy has catalog ID of 9906622777393393 and RA, DEC = 149.218121, 3.469923
2026-10-14 11:22:10,370- INFO - Conditioning association on the following properties: ['offset']

5/127 done: 2026fgl

2026-10-14 11:22:12,816- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:12,819- INFO -

Associating 2026fgt at RA, DEC = 186.188879, 6.589125 (redshift nan)
2026-10-14 11:22:14,733- INFO - Association successful!
2026-10-14 11:22:14,758- INFO -

Properties of best host (in decals dr9) for 2026fgt:
    objID: 9906623916018877
    R.A. (deg): 186.189092
    Dec. (deg): 6.589056
    Posterior: 1.0000e+00
    Redshift: 0.5220 ± 0.1206 (PHOT)
    Absolute Magnitude: -19.9 ± 1.1 (r)
    Transient Offset: 0.8 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:22:14,759- INFO -

Properties of 2nd best host (in decals dr9) for 2026fgt:
    Redshift: 0.2019 ± 0.0239 (PHOT)
    Absolute Magnitude: -21.8 ± 0.9 (r)
    Transient Offset: 299.2 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:14,759- INFO - Chosen galaxy has catalog ID of 9906623916018877 and RA, DEC = 186.189092, 6.589056
2026-10-14 11:22:14,772- INFO - Conditioning association on the following properties: ['offset']

6/127 done: 2026fgt

2026-10-14 11:22:16,846- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:16,848- INFO -

Associating 2026ewl at RA, DEC = 185.547821, 7.747500 (redshift nan)
2026-10-14 11:22:19,140- INFO - Association successful!
2026-10-14 11:22:19,172- INFO -

Properties of best host (in decals dr9) for 2026ewl:
    objID: 9906624384598107
    R.A. (deg): 185.547957
    Dec. (deg): 7.746464
    Posterior: 1.0000e+00
    Redshift: 0.1355 ± 0.0068 (SPEC)
    Absolute Magnitude: -22.5 ± 0.8 (r)
    Transient Offset: 3.8 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:22:19,172- INFO -

Properties of 2nd best host (in decals dr9) for 2026ewl:
    Redshift: 0.9054 ± 0.2016 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 298.3 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:19,172- INFO - Chosen galaxy has catalog ID of 9906624384598107 and RA, DEC = 185.547957, 7.746464
2026-10-14 11:22:19,182- INFO - Conditioning association on the following properties: ['offset']

7/127 done: 2026ewl

2026-10-14 11:22:21,167- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:21,169- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:22:23,434- INFO - Association successful!
2026-10-14 11:22:23,468- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9118e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9118e-01
2026-10-14 11:22:23,468- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:23,469- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:22:23,486- INFO - Conditioning association on the following properties: ['offset']

8/127 done: 2024bhx

2026-10-14 11:22:25,490- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:25,491- INFO -

Associating 2024adyk at RA, DEC = 186.016373, 8.411760 (redshift nan)
2026-10-14 11:22:27,117- INFO - Association successful!
2026-10-14 11:22:27,139- INFO -

Properties of best host (in decals dr9) for 2024adyk:
    objID: 9906624665227522
    R.A. (deg): 186.015520
    Dec. (deg): 8.410711
    Posterior: 7.3228e-01
    Redshift: 0.0771 ± 0.0039 (SPEC)
    Absolute Magnitude: -21.5 ± 0.8 (r)
    Transient Offset: 4.9 ± 0.1 arcsec
    Transient Offset Posterior: 7.3228e-01
2026-10-14 11:22:27,139- INFO -

Properties of 2nd best host (in decals dr9) for 2024adyk:
    Redshift: 0.8190 ± 0.1135 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:27,140- INFO - Chosen galaxy has catalog ID of 9906624665227522 and RA, DEC = 186.015520, 8.410711
2026-10-14 11:22:27,150- INFO - Conditioning association on the following properties: ['offset']

9/127 done: 2024adyk

2026-10-14 11:22:29,135- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:29,137- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:22:32,133- INFO - Association successful!
2026-10-14 11:22:32,163- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9521e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9521e-01
2026-10-14 11:22:32,163- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:32,163- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:22:32,175- INFO - Conditioning association on the following properties: ['offset']

10/127 done: 2024bhx

2026-10-14 11:22:34,175- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:34,177- INFO -

Associating 2024lah at RA, DEC = 185.996538, 7.725874 (redshift nan)
2026-10-14 11:22:36,347- INFO - Association successful!
2026-10-14 11:22:36,379- INFO -

Properties of best host (in decals dr9) for 2024lah:
    objID: 9906624384668493
    R.A. (deg): 185.996418
    Dec. (deg): 7.725895
    Posterior: 1.0000e+00
    Redshift: 0.0684 ± 0.0215 (PHOT)
    Absolute Magnitude: -19.4 ± 0.9 (r)
    Transient Offset: 0.4 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:22:36,379- INFO -

Properties of 2nd best host (in decals dr9) for 2024lah:
    Redshift: 1.1880 ± 0.3335 (PHOT)
    Absolute Magnitude: -20.1 ± 1.2 (r)
    Transient Offset: 296.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:36,380- INFO - Chosen galaxy has catalog ID of 9906624384668493 and RA, DEC = 185.996418, 7.725895
2026-10-14 11:22:36,390- INFO - Conditioning association on the following properties: ['offset']

11/127 done: 2024lah

2026-10-14 11:22:38,418- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:38,420- INFO -

Associating 2021hiz at RA, DEC = 186.423625, 7.228389 (redshift nan)
2026-10-14 11:22:40,407- INFO - Association successful!
2026-10-14 11:22:40,432- INFO -

Properties of best host (in decals dr9) for 2021hiz:
    objID: 9906624197430225
    R.A. (deg): 186.423926
    Dec. (deg): 7.226417
    Posterior: 8.4093e-01
    Redshift: 0.0364 ± 0.0182 (PHOT)
    Absolute Magnitude: -19.3 ± 0.8 (r)
    Transient Offset: 7.2 ± 0.1 arcsec
    Transient Offset Posterior: 8.4093e-01
2026-10-14 11:22:40,433- INFO -

Properties of 2nd best host (in decals dr9) for 2021hiz:
    Redshift: 1.2025 ± 0.5618 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:40,433- INFO - Chosen galaxy has catalog ID of 9906624197430225 and RA, DEC = 186.423926, 7.226417
2026-10-14 11:22:40,444- INFO - Conditioning association on the following properties: ['offset']

12/127 done: 2021hiz

2026-10-14 11:22:42,798- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:42,801- INFO -

Associating 2021ita at RA, DEC = 186.495177, 7.235433 (redshift nan)
2026-10-14 11:22:44,665- INFO - Association successful!
2026-10-14 11:22:44,689- INFO -

Properties of best host (in decals dr9) for 2021ita:
    objID: 9906624197431893
    R.A. (deg): 186.495065
    Dec. (deg): 7.235318
    Posterior: 9.9403e-01
    Redshift: 0.1510 ± 0.0188 (PHOT)
    Absolute Magnitude: -21.5 ± 0.9 (r)
    Transient Offset: 0.6 ± 0.1 arcsec
    Transient Offset Posterior: 9.9403e-01
2026-10-14 11:22:44,690- INFO -

Properties of 2nd best host (in decals dr9) for 2021ita:
    Redshift: 0.6744 ± 0.1422 (PHOT)
    Absolute Magnitude: -20.4 ± 1.1 (r)
    Transient Offset: 296.7 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:44,690- INFO - Chosen galaxy has catalog ID of 9906624197431893 and RA, DEC = 186.495065, 7.235318
2026-10-14 11:22:44,707- INFO - Conditioning association on the following properties: ['offset']

13/127 done: 2021ita

2026-10-14 11:22:46,682- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:46,683- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:22:49,091- INFO - Association successful!
2026-10-14 11:22:49,121- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9669e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9669e-01
2026-10-14 11:22:49,121- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:49,121- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:22:49,133- INFO - Conditioning association on the following properties: ['offset']

14/127 done: 2024bhx

2026-10-14 11:22:50,999- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:51,000- INFO -

Associating 2024lah at RA, DEC = 185.996538, 7.725874 (redshift nan)
2026-10-14 11:22:53,280- INFO - Association successful!
2026-10-14 11:22:53,311- INFO -

Properties of best host (in decals dr9) for 2024lah:
    objID: 9906624384668493
    R.A. (deg): 185.996418
    Dec. (deg): 7.725895
    Posterior: 1.0000e+00
    Redshift: 0.0684 ± 0.0215 (PHOT)
    Absolute Magnitude: -19.4 ± 0.9 (r)
    Transient Offset: 0.4 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:22:53,311- INFO -

Properties of 2nd best host (in decals dr9) for 2024lah:
    Redshift: 1.1880 ± 0.3335 (PHOT)
    Absolute Magnitude: -20.1 ± 1.2 (r)
    Transient Offset: 296.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:53,311- INFO - Chosen galaxy has catalog ID of 9906624384668493 and RA, DEC = 185.996418, 7.725895
2026-10-14 11:22:53,321- INFO - Conditioning association on the following properties: ['offset']

15/127 done: 2024lah

2026-10-14 11:22:55,236- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:55,238- INFO -

Associating 2024adyk at RA, DEC = 186.016373, 8.411760 (redshift nan)
2026-10-14 11:22:56,953- INFO - Association successful!
2026-10-14 11:22:56,974- INFO -

Properties of best host (in decals dr9) for 2024adyk:
    objID: 9906624665227522
    R.A. (deg): 186.015520
    Dec. (deg): 8.410711
    Posterior: 7.3231e-01
    Redshift: 0.0771 ± 0.0039 (SPEC)
    Absolute Magnitude: -21.5 ± 0.8 (r)
    Transient Offset: 4.9 ± 0.1 arcsec
    Transient Offset Posterior: 7.3231e-01
2026-10-14 11:22:56,975- INFO -

Properties of 2nd best host (in decals dr9) for 2024adyk:
    Redshift: 0.8190 ± 0.1135 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:22:56,975- INFO - Chosen galaxy has catalog ID of 9906624665227522 and RA, DEC = 186.015520, 8.410711
2026-10-14 11:22:56,985- INFO - Conditioning association on the following properties: ['offset']

16/127 done: 2024adyk

2026-10-14 11:22:58,914- INFO - Loaded GLADE+ catalog.
2026-10-14 11:22:58,916- INFO -

Associating 2021hiz at RA, DEC = 186.423625, 7.228389 (redshift nan)
2026-10-14 11:23:00,752- INFO - Association successful!
2026-10-14 11:23:00,778- INFO -

Properties of best host (in decals dr9) for 2021hiz:
    objID: 9906624197430225
    R.A. (deg): 186.423926
    Dec. (deg): 7.226417
    Posterior: 8.4043e-01
    Redshift: 0.0364 ± 0.0182 (PHOT)
    Absolute Magnitude: -19.3 ± 0.8 (r)
    Transient Offset: 7.2 ± 0.1 arcsec
    Transient Offset Posterior: 8.4043e-01
2026-10-14 11:23:00,778- INFO -

Properties of 2nd best host (in decals dr9) for 2021hiz:
    Redshift: 1.2025 ± 0.5618 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:00,778- INFO - Chosen galaxy has catalog ID of 9906624197430225 and RA, DEC = 186.423926, 7.226417
2026-10-14 11:23:00,790- INFO - Conditioning association on the following properties: ['offset']

17/127 done: 2021hiz

2026-10-14 11:23:02,740- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:02,742- INFO -

Associating 2021hiz at RA, DEC = 186.423625, 7.228389 (redshift nan)
2026-10-14 11:23:05,336- INFO - Association successful!
2026-10-14 11:23:05,361- INFO -

Properties of best host (in decals dr9) for 2021hiz:
    objID: 9906624197430225
    R.A. (deg): 186.423926
    Dec. (deg): 7.226417
    Posterior: 8.4022e-01
    Redshift: 0.0364 ± 0.0182 (PHOT)
    Absolute Magnitude: -19.3 ± 0.8 (r)
    Transient Offset: 7.2 ± 0.1 arcsec
    Transient Offset Posterior: 8.4022e-01
2026-10-14 11:23:05,361- INFO -

Properties of 2nd best host (in decals dr9) for 2021hiz:
    Redshift: 1.2025 ± 0.5618 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:05,361- INFO - Chosen galaxy has catalog ID of 9906624197430225 and RA, DEC = 186.423926, 7.226417
2026-10-14 11:23:05,371- INFO - Conditioning association on the following properties: ['offset']

18/127 done: 2021hiz

2026-10-14 11:23:07,264- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:07,266- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:23:09,520- INFO - Association successful!
2026-10-14 11:23:09,550- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9081e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9081e-01
2026-10-14 11:23:09,550- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:09,550- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:23:09,561- INFO - Conditioning association on the following properties: ['offset']

19/127 done: 2024bhx

2026-10-14 11:23:11,542- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:11,543- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:23:13,695- INFO - Association successful!
2026-10-14 11:23:13,725- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9308e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9308e-01
2026-10-14 11:23:13,725- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:13,725- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:23:13,736- INFO - Conditioning association on the following properties: ['offset']

20/127 done: 2024bhx

2026-10-14 11:23:16,705- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:16,710- INFO -

Associating 2024lah at RA, DEC = 185.996538, 7.725874 (redshift nan)
2026-10-14 11:23:18,976- INFO - Association successful!
2026-10-14 11:23:19,006- INFO -

Properties of best host (in decals dr9) for 2024lah:
    objID: 9906624384668493
    R.A. (deg): 185.996418
    Dec. (deg): 7.725895
    Posterior: 1.0000e+00
    Redshift: 0.0684 ± 0.0215 (PHOT)
    Absolute Magnitude: -19.4 ± 0.9 (r)
    Transient Offset: 0.5 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:23:19,006- INFO -

Properties of 2nd best host (in decals dr9) for 2024lah:
    Redshift: 1.1880 ± 0.3335 (PHOT)
    Absolute Magnitude: -20.1 ± 1.2 (r)
    Transient Offset: 296.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:19,007- INFO - Chosen galaxy has catalog ID of 9906624384668493 and RA, DEC = 185.996418, 7.725895
2026-10-14 11:23:19,021- INFO - Conditioning association on the following properties: ['offset']

21/127 done: 2024lah

2026-10-14 11:23:21,041- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:21,042- INFO -

Associating 2021ita at RA, DEC = 186.495177, 7.235433 (redshift nan)
2026-10-14 11:23:22,886- INFO - Association successful!
2026-10-14 11:23:22,910- INFO -

Properties of best host (in decals dr9) for 2021ita:
    objID: 9906624197431893
    R.A. (deg): 186.495065
    Dec. (deg): 7.235318
    Posterior: 9.9426e-01
    Redshift: 0.1510 ± 0.0188 (PHOT)
    Absolute Magnitude: -21.5 ± 0.9 (r)
    Transient Offset: 0.6 ± 0.1 arcsec
    Transient Offset Posterior: 9.9426e-01
2026-10-14 11:23:22,910- INFO -

Properties of 2nd best host (in decals dr9) for 2021ita:
    Redshift: 0.6744 ± 0.1422 (PHOT)
    Absolute Magnitude: -20.4 ± 1.1 (r)
    Transient Offset: 296.7 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:22,910- INFO - Chosen galaxy has catalog ID of 9906624197431893 and RA, DEC = 186.495065, 7.235318
2026-10-14 11:23:22,948- INFO - Conditioning association on the following properties: ['offset']

22/127 done: 2021ita

2026-10-14 11:23:24,920- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:24,922- INFO -

Associating 2024lah at RA, DEC = 185.996538, 7.725874 (redshift nan)
2026-10-14 11:23:26,994- INFO - Association successful!
2026-10-14 11:23:27,024- INFO -

Properties of best host (in decals dr9) for 2024lah:
    objID: 9906624384668493
    R.A. (deg): 185.996418
    Dec. (deg): 7.725895
    Posterior: 1.0000e+00
    Redshift: 0.0684 ± 0.0215 (PHOT)
    Absolute Magnitude: -19.4 ± 0.9 (r)
    Transient Offset: 0.5 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:23:27,025- INFO -

Properties of 2nd best host (in decals dr9) for 2024lah:
    Redshift: 1.1880 ± 0.3335 (PHOT)
    Absolute Magnitude: -20.1 ± 1.2 (r)
    Transient Offset: 296.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:27,025- INFO - Chosen galaxy has catalog ID of 9906624384668493 and RA, DEC = 185.996418, 7.725895
2026-10-14 11:23:27,040- INFO - Conditioning association on the following properties: ['offset']

23/127 done: 2024lah

2026-10-14 11:23:28,910- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:28,911- INFO -

Associating 2026ekf at RA, DEC = 187.707737, 8.273932 (redshift nan)
2026-10-14 11:23:31,503- INFO - Association successful!
2026-10-14 11:23:31,527- INFO -

Properties of best host (in decals dr9) for 2026ekf:
    objID: 9906624572230448
    R.A. (deg): 187.707788
    Dec. (deg): 8.273854
    Posterior: 9.9994e-01
    Redshift: 0.2933 ± 0.1099 (PHOT)
    Absolute Magnitude: -19.2 ± 1.1 (r)
    Transient Offset: 0.4 ± 0.1 arcsec
    Transient Offset Posterior: 9.9994e-01
2026-10-14 11:23:31,527- INFO -

Properties of 2nd best host (in decals dr9) for 2026ekf:
    Redshift: 0.3727 ± 0.1018 (PHOT)
    Absolute Magnitude: -19.5 ± 1.1 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:31,527- INFO - Chosen galaxy has catalog ID of 9906624572230448 and RA, DEC = 187.707788, 8.273854
2026-10-14 11:23:31,537- INFO - Conditioning association on the following properties: ['offset']

24/127 done: 2026ekf

2026-10-14 11:23:33,377- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:33,378- INFO -

Associating 2021hiz at RA, DEC = 186.423625, 7.228389 (redshift nan)
2026-10-14 11:23:35,375- INFO - Association successful!
2026-10-14 11:23:35,400- INFO -

Properties of best host (in decals dr9) for 2021hiz:
    objID: 9906624197430225
    R.A. (deg): 186.423926
    Dec. (deg): 7.226417
    Posterior: 8.4114e-01
    Redshift: 0.0364 ± 0.0182 (PHOT)
    Absolute Magnitude: -19.3 ± 0.8 (r)
    Transient Offset: 7.2 ± 0.1 arcsec
    Transient Offset Posterior: 8.4114e-01
2026-10-14 11:23:35,400- INFO -

Properties of 2nd best host (in decals dr9) for 2021hiz:
    Redshift: 1.2025 ± 0.5618 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:35,401- INFO - Chosen galaxy has catalog ID of 9906624197430225 and RA, DEC = 186.423926, 7.226417
2026-10-14 11:23:35,412- INFO - Conditioning association on the following properties: ['offset']

25/127 done: 2021hiz

2026-10-14 11:23:37,266- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:37,267- INFO -

Associating 2026kjm at RA, DEC = 186.147455, 7.728034 (redshift nan)
2026-10-14 11:23:39,343- INFO - Association successful!
2026-10-14 11:23:39,370- INFO -

Properties of best host (in decals dr9) for 2026kjm:
    objID: 9906624384731883
    R.A. (deg): 186.147688
    Dec. (deg): 7.727766
    Posterior: 1.0000e+00
    Redshift: 0.1004 ± 0.0194 (PHOT)
    Absolute Magnitude: -19.5 ± 0.9 (r)
    Transient Offset: 1.3 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:23:39,371- INFO -

Properties of 2nd best host (in decals dr9) for 2026kjm:
    Redshift: 1.0555 ± 0.4803 (PHOT)
    Absolute Magnitude: -20.8 ± 1.2 (r)
    Transient Offset: 293.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:39,371- INFO - Chosen galaxy has catalog ID of 9906624384731883 and RA, DEC = 186.147688, 7.727766
2026-10-14 11:23:39,383- INFO - Conditioning association on the following properties: ['offset']

26/127 done: 2026kjm

2026-10-14 11:23:41,379- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:41,384- INFO -

Associating 2021ita at RA, DEC = 186.495177, 7.235433 (redshift nan)
2026-10-14 11:23:43,198- INFO - Association successful!
2026-10-14 11:23:43,223- INFO -

Properties of best host (in decals dr9) for 2021ita:
    objID: 9906624197431893
    R.A. (deg): 186.495065
    Dec. (deg): 7.235318
    Posterior: 9.9407e-01
    Redshift: 0.1510 ± 0.0188 (PHOT)
    Absolute Magnitude: -21.5 ± 0.9 (r)
    Transient Offset: 0.6 ± 0.1 arcsec
    Transient Offset Posterior: 9.9407e-01
2026-10-14 11:23:43,223- INFO -

Properties of 2nd best host (in decals dr9) for 2021ita:
    Redshift: 0.6744 ± 0.1422 (PHOT)
    Absolute Magnitude: -20.4 ± 1.1 (r)
    Transient Offset: 296.7 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:43,223- INFO - Chosen galaxy has catalog ID of 9906624197431893 and RA, DEC = 186.495065, 7.235318
2026-10-14 11:23:43,234- INFO - Conditioning association on the following properties: ['offset']

27/127 done: 2021ita

2026-10-14 11:23:45,220- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:45,221- INFO -

Associating 2026kjm at RA, DEC = 186.147455, 7.728034 (redshift nan)
2026-10-14 11:23:47,426- INFO - Association successful!
2026-10-14 11:23:47,452- INFO -

Properties of best host (in decals dr9) for 2026kjm:
    objID: 9906624384731883
    R.A. (deg): 186.147688
    Dec. (deg): 7.727766
    Posterior: 1.0000e+00
    Redshift: 0.1004 ± 0.0194 (PHOT)
    Absolute Magnitude: -19.5 ± 0.9 (r)
    Transient Offset: 1.3 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:23:47,453- INFO -

Properties of 2nd best host (in decals dr9) for 2026kjm:
    Redshift: 1.0555 ± 0.4803 (PHOT)
    Absolute Magnitude: -20.8 ± 1.2 (r)
    Transient Offset: 293.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:47,453- INFO - Chosen galaxy has catalog ID of 9906624384731883 and RA, DEC = 186.147688, 7.727766
2026-10-14 11:23:47,463- INFO - Conditioning association on the following properties: ['offset']

28/127 done: 2026kjm

2026-10-14 11:23:49,373- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:49,374- INFO -

Associating 2021hiz at RA, DEC = 186.423625, 7.228389 (redshift nan)
2026-10-14 11:23:51,473- INFO - Association successful!
2026-10-14 11:23:51,498- INFO -

Properties of best host (in decals dr9) for 2021hiz:
    objID: 9906624197430225
    R.A. (deg): 186.423926
    Dec. (deg): 7.226417
    Posterior: 8.4078e-01
    Redshift: 0.0364 ± 0.0182 (PHOT)
    Absolute Magnitude: -19.3 ± 0.8 (r)
    Transient Offset: 7.2 ± 0.1 arcsec
    Transient Offset Posterior: 8.4078e-01
2026-10-14 11:23:51,499- INFO -

Properties of 2nd best host (in decals dr9) for 2021hiz:
    Redshift: 1.2025 ± 0.5618 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:51,499- INFO - Chosen galaxy has catalog ID of 9906624197430225 and RA, DEC = 186.423926, 7.226417
2026-10-14 11:23:51,510- INFO - Conditioning association on the following properties: ['offset']

29/127 done: 2021hiz

2026-10-14 11:23:53,527- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:53,529- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:23:55,831- INFO - Association successful!
2026-10-14 11:23:55,864- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9126e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9126e-01
2026-10-14 11:23:55,865- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:55,865- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:23:55,877- INFO - Conditioning association on the following properties: ['offset']

30/127 done: 2024bhx

2026-10-14 11:23:58,081- INFO - Loaded GLADE+ catalog.
2026-10-14 11:23:58,086- INFO -

Associating 2021hiz at RA, DEC = 186.423625, 7.228389 (redshift nan)
2026-10-14 11:23:59,902- INFO - Association successful!
2026-10-14 11:23:59,927- INFO -

Properties of best host (in decals dr9) for 2021hiz:
    objID: 9906624197430225
    R.A. (deg): 186.423926
    Dec. (deg): 7.226417
    Posterior: 8.4103e-01
    Redshift: 0.0364 ± 0.0182 (PHOT)
    Absolute Magnitude: -19.3 ± 0.8 (r)
    Transient Offset: 7.2 ± 0.1 arcsec
    Transient Offset Posterior: 8.4103e-01
2026-10-14 11:23:59,928- INFO -

Properties of 2nd best host (in decals dr9) for 2021hiz:
    Redshift: 1.2025 ± 0.5618 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:23:59,928- INFO - Chosen galaxy has catalog ID of 9906624197430225 and RA, DEC = 186.423926, 7.226417
2026-10-14 11:23:59,979- INFO - Conditioning association on the following properties: ['offset']

31/127 done: 2021hiz

2026-10-14 11:24:02,028- INFO - Loaded GLADE+ catalog.
2026-10-14 11:24:02,030- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:24:04,899- INFO - Association successful!
2026-10-14 11:24:04,929- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9376e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9376e-01
2026-10-14 11:24:04,929- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:24:04,929- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:24:04,940- INFO - Conditioning association on the following properties: ['offset']

32/127 done: 2024bhx

2026-10-14 11:24:06,837- INFO - Loaded GLADE+ catalog.
2026-10-14 11:24:06,839- INFO -

Associating 2023dyl at RA, DEC = 150.744415, 2.343412 (redshift nan)
2026-10-14 11:24:12,472- INFO - Association successful!
2026-10-14 11:24:12,497- INFO -

Properties of best host (in decals dr9) for 2023dyl:
    objID: 9906622306063990
    R.A. (deg): 150.746064
    Dec. (deg): 2.343021
    Posterior: 8.4808e-01
    Redshift: 0.0328 ± 0.0065 (PHOT)
    Absolute Magnitude: -21.6 ± 0.7 (r)
    Transient Offset: 6.1 ± 0.1 arcsec
    Transient Offset Posterior: 8.4808e-01
2026-10-14 11:24:12,497- INFO -

Properties of 2nd best host (in decals dr9) for 2023dyl:
    Redshift: 0.6788 ± 0.2611 (PHOT)
    Absolute Magnitude: -19.8 ± 1.2 (r)
    Transient Offset: 294.0 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:24:12,497- INFO - Chosen galaxy has catalog ID of 9906622306063990 and RA, DEC = 150.746064, 2.343021
2026-10-14 11:24:12,509- INFO - Conditioning association on the following properties: ['offset']

33/127 done: 2023dyl

2026-10-14 11:24:14,426- INFO - Loaded GLADE+ catalog.
2026-10-14 11:24:14,428- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:24:16,679- INFO - Association successful!
2026-10-14 11:24:16,710- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9102e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9102e-01
2026-10-14 11:24:16,711- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:24:16,711- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:24:16,722- INFO - Conditioning association on the following properties: ['offset']

34/127 done: 2024bhx

2026-10-14 11:24:18,805- INFO - Loaded GLADE+ catalog.
2026-10-14 11:24:18,808- INFO -

Associating 2021ita at RA, DEC = 186.495177, 7.235433 (redshift nan)
2026-10-14 11:24:20,850- INFO - Association successful!
2026-10-14 11:24:20,874- INFO -

Properties of best host (in decals dr9) for 2021ita:
    objID: 9906624197431893
    R.A. (deg): 186.495065
    Dec. (deg): 7.235318
    Posterior: 9.9406e-01
    Redshift: 0.1510 ± 0.0188 (PHOT)
    Absolute Magnitude: -21.5 ± 0.9 (r)
    Transient Offset: 0.6 ± 0.1 arcsec
    Transient Offset Posterior: 9.9406e-01
2026-10-14 11:24:20,874- INFO -

Properties of 2nd best host (in decals dr9) for 2021ita:
    Redshift: 0.6744 ± 0.1422 (PHOT)
    Absolute Magnitude: -20.4 ± 1.1 (r)
    Transient Offset: 296.7 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:24:20,875- INFO - Chosen galaxy has catalog ID of 9906624197431893 and RA, DEC = 186.495065, 7.235318
2026-10-14 11:24:20,887- INFO - Conditioning association on the following properties: ['offset']

35/127 done: 2021ita

2026-10-14 11:24:22,874- INFO - Loaded GLADE+ catalog.
2026-10-14 11:24:22,875- INFO -

Associating 2026fgl at RA, DEC = 149.218165, 3.469919 (redshift nan)
2026-10-14 11:24:24,389- INFO - Association successful!
2026-10-14 11:24:24,406- INFO -

Properties of best host (in decals dr9) for 2026fgl:
    objID: 9906622777393393
    R.A. (deg): 149.218121
    Dec. (deg): 3.469923
    Posterior: 1.0000e+00
    Redshift: 0.1643 ± 0.0082 (SPEC)
    Absolute Magnitude: -22.3 ± 0.9 (r)
    Transient Offset: 0.2 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:24:24,407- INFO -

Properties of 2nd best host (in decals dr9) for 2026fgl:
    Redshift: 0.9634 ± 0.1610 (PHOT)
    Absolute Magnitude: -20.6 ± 1.2 (r)
    Transient Offset: 297.4 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:24:24,407- INFO - Chosen galaxy has catalog ID of 9906622777393393 and RA, DEC = 149.218121, 3.469923
2026-10-14 11:24:24,417- INFO - Conditioning association on the following properties: ['offset']

36/127 done: 2026fgl

2026-10-14 11:24:26,286- INFO - Loaded GLADE+ catalog.
2026-10-14 11:24:26,287- INFO -

Associating 2026fbm at RA, DEC = 150.032600, 3.024186 (redshift nan)
2026-10-14 11:24:28,512- INFO - Association successful!
2026-10-14 11:24:28,541- INFO -

Properties of best host (in decals dr9) for 2026fbm:
    objID: 9906622589043609
    R.A. (deg): 150.032161
    Dec. (deg): 3.024137
    Posterior: 1.0000e+00
    Redshift: 0.2602 ± 0.1301 (PHOT)
    Absolute Magnitude: -19.6 ± 1.1 (r)
    Transient Offset: 1.6 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:24:28,541- INFO -

Properties of 2nd best host (in decals dr9) for 2026fbm:
    Redshift: 1.0686 ± 0.5343 (PHOT)
    Absolute Magnitude: -20.2 ± 1.2 (r)
    Transient Offset: 299.6 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:24:28,541- INFO - Chosen galaxy has catalog ID of 9906622589043609 and RA, DEC = 150.032161, 3.024137
2026-10-14 11:24:28,552- INFO - Conditioning association on the following properties: ['offset']

37/127 done: 2026fbm

2026-10-14 11:24:30,691- INFO - Loaded GLADE+ catalog.
2026-10-14 11:24:30,693- INFO -

Associating 2026ezw at RA, DEC = 149.635687, 1.269344 (redshift nan)
2026-10-14 11:24:33,696- INFO - Association successful!
2026-10-14 11:24:33,733- INFO -

Properties of best host (in decals dr9) for 2026ezw:
    objID: 9906621928311970
    R.A. (deg): 149.635776
    Dec. (deg): 1.269511
    Posterior: 9.9993e-01
    Redshift: 0.1937 ± 0.0311 (PHOT)
    Absolute Magnitude: -21.3 ± 0.9 (r)
    Transient Offset: 0.7 ± 0.1 arcsec
    Transient Offset Posterior: 9.9993e-01
2026-10-14 11:24:33,734- INFO -

Properties of 2nd best host (in decals dr9) for 2026ezw:
    Redshift: 1.0017 ± 0.3546 (PHOT)
    Absolute Magnitude: -21.0 ± 1.2 (r)
    Transient Offset: 298.3 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:24:33,734- INFO - Chosen galaxy has catalog ID of 9906621928311970 and RA, DEC = 149.635776, 1.269511
2026-10-14 11:24:33,753- INFO - Conditioning association on the following properties: ['offset']

38/127 done: 2026ezw

2026-10-14 11:24:37,407- INFO - Loaded GLADE+ catalog.
2026-10-14 11:24:37,421- INFO -

Associating 2026ikn at RA, DEC = 149.943679, 3.780242 (redshift nan)
2026-10-14 11:24:41,161- INFO - Association successful!
2026-10-14 11:24:41,186- INFO -

Properties of best host (in decals dr9) for 2026ikn:
    objID: 9906622871769883
    R.A. (deg): 149.943689
    Dec. (deg): 3.780043
    Posterior: 1.0000e+00
    Redshift: 0.2276 ± 0.0430 (PHOT)
    Absolute Magnitude: -20.0 ± 1.0 (r)
    Transient Offset: 0.7 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:24:41,187- INFO -

Properties of 2nd best host (in decals dr9) for 2026ikn:
    Redshift: 0.8858 ± 0.4429 (PHOT)
    Absolute Magnitude: -20.7 ± 1.2 (r)
    Transient Offset: 295.2 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:24:41,187- INFO - Chosen galaxy has catalog ID of 9906622871769883 and RA, DEC = 149.943689, 3.780043
2026-10-14 11:24:41,202- INFO - Conditioning association on the following properties: ['offset']

39/127 done: 2026ikn

2026-10-14 11:24:43,574- INFO - Loaded GLADE+ catalog.
2026-10-14 11:24:43,577- INFO -

Associating 2026ftl at RA, DEC = 188.402327, 6.368380 (redshift nan)
2026-10-14 11:24:47,044- INFO - Association successful!
2026-10-14 11:24:47,067- INFO -

Properties of best host (in decals dr9) for 2026ftl:
    objID: 9906623822760158
    R.A. (deg): 188.402259
    Dec. (deg): 6.368652
    Posterior: 1.0000e+00
    Redshift: 0.3447 ± 0.1104 (PHOT)
    Absolute Magnitude: -20.0 ± 1.1 (r)
    Transient Offset: 1.0 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:24:47,067- INFO -

Properties of 2nd best host (in decals dr9) for 2026ftl:
    objID: 9906623822759252
    R.A. (deg): 188.356962
    Dec. (deg): 6.368931
    Posterior: 0.0000e+00
    Redshift: 0.7597 ± 0.1346 (PHOT)
    Absolute Magnitude: -20.4 ± 1.1 (r)
    Transient Offset: 162.3 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:24:47,067- INFO - Chosen galaxy has catalog ID of 9906623822760158 and RA, DEC = 188.402259, 6.368652
2026-10-14 11:24:47,085- INFO - Conditioning association on the following properties: ['offset']

40/127 done: 2026ftl

2026-10-14 11:24:49,218- INFO - Loaded GLADE+ catalog.
2026-10-14 11:24:49,222- INFO -

Associating 2026ivl at RA, DEC = 148.474283, 1.718233 (redshift nan)
2026-10-14 11:24:51,149- INFO - Association successful!
2026-10-14 11:24:51,172- INFO -

Properties of best host (in decals dr9) for 2026ivl:
    objID: 9906622116729406
    R.A. (deg): 148.474148
    Dec. (deg): 1.719041
    Posterior: 6.3103e-01
    Redshift: 0.1035 ± 0.0247 (PHOT)
    Absolute Magnitude: -19.3 ± 1.0 (r)
    Transient Offset: 2.9 ± 0.1 arcsec
    Transient Offset Posterior: 6.3103e-01
2026-10-14 11:24:51,172- INFO -

Properties of 2nd best host (in decals dr9) for 2026ivl:
    Redshift: 1.0438 ± 0.2868 (PHOT)
    Absolute Magnitude: -20.8 ± 1.2 (r)
    Transient Offset: 299.0 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:24:51,172- INFO - Chosen galaxy has catalog ID of 9906622116729406 and RA, DEC = 148.474148, 1.719041
2026-10-14 11:24:51,188- INFO - Conditioning association on the following properties: ['offset']

41/127 done: 2026ivl

2026-10-14 11:24:53,227- INFO - Loaded GLADE+ catalog.
2026-10-14 11:24:53,229- INFO -

Associating 2026kfw at RA, DEC = 149.219885, 1.833104 (redshift nan)
2026-10-14 11:24:55,053- WARNING - Association failed. Host is likely outside the search cone.
2026-10-14 11:24:55,079- INFO - Running with shred_cut = True...
2026-10-14 11:24:59,847- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:24:59,967- INFO - Removed 2 flagged panstarrs sources.
2026-10-14 11:24:59,995- WARNING - Association failed. Host is likely outside the search cone.
Traceback (most recent call last):
  File "/var/folders/w3/zfhnfs711s5c81b047h4v6jm0000gn/T/ipykernel_38615/282781924.py", line 38, in <module>
    result = associate_sample(
    one_transient,
    ...<7 lines>...
    save=False,
    )
  File "/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/astro_prost/associate.py", line 759, in associate_sample
    results[i] = associate_transient(*event)
                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/astro_prost/associate.py", line 440, in associate_transient
    cat.get_candidates(transient, time_query=True, logger=logger, cosmo=cosmo, calc_host_props=calc_host_props_cat, cat_cols=cat_cols)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/astro_prost/helpers.py", line 1073, in get_candidates
    self.galaxies, self.cat_col_fields = fetch_catalog_data(self, transient, search_rad, cosmo, logger, cat_cols, calc_host_props)
                                         ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/astro_prost/helpers.py", line 991, in fetch_catalog_data
    return catalog_func(**init_params)
  File "/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/astro_prost/helpers.py", line 2555, in build_skymapper_candidates
    temp_mag_r_std[temp_mag_r_std > (SIGMA_ABSMAG_CEIL*temp_mag_r)] = SIGMA_ABSMAG_CEIL * temp_mag_r[temp_mag_r_std > (SIGMA_ABSMAG_CEIL*temp_mag_r)]
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: assignment destination is read-only
2026-10-14 11:25:11,872- INFO - Conditioning association on the following properties: ['offset']

42/127 failed: 2026kfw: assignment destination is read-only

2026-10-14 11:25:14,007- INFO - Loaded GLADE+ catalog.
2026-10-14 11:25:14,010- INFO -

Associating 2026mza at RA, DEC = 151.163533, 2.507447 (redshift nan)
2026-10-14 11:25:15,943- INFO - Association successful!
2026-10-14 11:25:15,964- INFO -

Properties of best host (in decals dr9) for 2026mza:
    objID: 9906622400564674
    R.A. (deg): 151.162837
    Dec. (deg): 2.507195
    Posterior: 9.9938e-01
    Redshift: 0.1447 ± 0.0254 (PHOT)
    Absolute Magnitude: -20.2 ± 0.9 (r)
    Transient Offset: 2.7 ± 0.1 arcsec
    Transient Offset Posterior: 9.9938e-01
2026-10-14 11:25:15,964- INFO -

Properties of 2nd best host (in decals dr9) for 2026mza:
    objID: 9906622400564708
    R.A. (deg): 151.164732
    Dec. (deg): 2.427948
    Posterior: 0.0000e+00
    Redshift: 0.4882 ± 0.1005 (PHOT)
    Absolute Magnitude: -19.9 ± 1.1 (r)
    Transient Offset: 286.2 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:25:15,964- INFO - Chosen galaxy has catalog ID of 9906622400564674 and RA, DEC = 151.162837, 2.507195
2026-10-14 11:25:15,974- INFO - Conditioning association on the following properties: ['offset']

43/127 done: 2026mza

2026-10-14 11:25:18,009- INFO - Loaded GLADE+ catalog.
2026-10-14 11:25:18,010- INFO -

Associating 2026lap at RA, DEC = 242.956759, -12.334252 (redshift nan)
2026-10-14 11:25:18,485- INFO - Running with shred_cut = True...
2026-10-14 11:25:24,319- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:25:24,450- INFO - Removed 1 flagged panstarrs sources.
2026-10-14 11:25:24,502- INFO - Association successful!
2026-10-14 11:25:24,520- INFO -

Properties of best host (in panstarrs dr2) for 2026lap:
    objID: 93192429568449336
    R.A. (deg): 242.956790
    Dec. (deg): -12.334211
    Posterior: 9.9858e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 0.2 ± 0.1 arcsec
    Transient Offset Posterior: 9.9858e-01
2026-10-14 11:25:24,521- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026lap:
    objID: 93222429027949096
    R.A. (deg): 242.902784
    Dec. (deg): -12.309404
    Posterior: 0.0000e+00
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 209.9 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:25:24,521- INFO - Chosen galaxy has catalog ID of 93192429568449336 and RA, DEC = 242.956790, -12.334211
2026-10-14 11:25:24,531- INFO - Conditioning association on the following properties: ['offset']

44/127 done: 2026lap

2026-10-14 11:25:26,523- INFO - Loaded GLADE+ catalog.
2026-10-14 11:25:26,524- INFO -

Associating 2026noz at RA, DEC = 244.644879, -11.884167 (redshift nan)
2026-10-14 11:25:27,077- INFO - Running with shred_cut = True...
2026-10-14 11:25:32,496- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:25:32,653- INFO - Removed 2 flagged panstarrs sources.
2026-10-14 11:25:32,713- INFO - Association successful!
2026-10-14 11:25:32,733- INFO -

Properties of best host (in panstarrs dr2) for 2026noz:
    objID: 93742446497243524
    R.A. (deg): 244.649815
    Dec. (deg): -11.880629
    Posterior: 3.1904e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 21.6 ± 0.1 arcsec
    Transient Offset Posterior: 3.1904e-01
2026-10-14 11:25:32,733- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026noz:
    objID: 93732446402538696
    R.A. (deg): 244.640246
    Dec. (deg): -11.884755
    Posterior: 2.2209e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 16.5 ± 0.1 arcsec
    Transient Offset Posterior: 2.2209e-01
2026-10-14 11:25:32,734- INFO - Chosen galaxy has catalog ID of 93742446497243524 and RA, DEC = 244.649815, -11.880629
2026-10-14 11:25:32,747- INFO - Conditioning association on the following properties: ['offset']

45/127 done: 2026noz

2026-10-14 11:25:34,739- INFO - Loaded GLADE+ catalog.
2026-10-14 11:25:34,740- INFO -

Associating 2026lqk at RA, DEC = 247.499936, -11.946715 (redshift nan)
2026-10-14 11:25:35,121- INFO - Running with shred_cut = True...
2026-10-14 11:25:42,030- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:25:42,209- INFO - Removed 1 flagged panstarrs sources.
2026-10-14 11:25:42,275- INFO - Association successful!
2026-10-14 11:25:42,301- INFO -

Properties of best host (in panstarrs dr2) for 2026lqk:
    objID: 93662474999664246
    R.A. (deg): 247.499922
    Dec. (deg): -11.946747
    Posterior: 9.9422e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 0.2 ± 0.1 arcsec
    Transient Offset Posterior: 9.9422e-01
2026-10-14 11:25:42,302- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026lqk:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 285.4 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:25:42,302- INFO - Chosen galaxy has catalog ID of 93662474999664246 and RA, DEC = 247.499922, -11.946747
2026-10-14 11:25:42,314- INFO - Conditioning association on the following properties: ['offset']

46/127 done: 2026lqk

2026-10-14 11:25:44,510- INFO - Loaded GLADE+ catalog.
2026-10-14 11:25:44,512- INFO -

Associating 2026oay at RA, DEC = 315.393989, -14.298573 (redshift nan)
2026-10-14 11:25:44,932- INFO - Running with shred_cut = True...
2026-10-14 11:25:49,758- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:25:49,858- INFO - Removed 3 flagged panstarrs sources.
2026-10-14 11:25:49,896- INFO - Association successful!
2026-10-14 11:25:49,910- INFO -

Properties of best host (in panstarrs dr2) for 2026oay:
    objID: 90843153933041877
    R.A. (deg): 315.393309
    Dec. (deg): -14.298732
    Posterior: 9.9975e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 2.4 ± 0.1 arcsec
    Transient Offset Posterior: 9.9975e-01
2026-10-14 11:25:49,910- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026oay:
    objID: 90903153343811171
    R.A. (deg): 315.334366
    Dec. (deg): -14.249293
    Posterior: 0.0000e+00
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 273.4 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:25:49,911- INFO - Chosen galaxy has catalog ID of 90843153933041877 and RA, DEC = 315.393309, -14.298732
2026-10-14 11:25:49,922- INFO - Conditioning association on the following properties: ['offset']

47/127 done: 2026oay

2026-10-14 11:25:51,935- INFO - Loaded GLADE+ catalog.
2026-10-14 11:25:51,936- INFO -

Associating 2025nxh at RA, DEC = 314.824097, -7.434222 (redshift nan)
2026-10-14 11:25:53,621- INFO - Association successful!
2026-10-14 11:25:53,641- INFO -

Properties of best host (in decals dr9) for 2025nxh:
    objID: 9906618674450204
    R.A. (deg): 314.822865
    Dec. (deg): -7.433470
    Posterior: 9.9647e-01
    Redshift: 0.0808 ± 0.0040 (SPEC)
    Absolute Magnitude: -22.4 ± 0.8 (r)
    Transient Offset: 5.2 ± 0.1 arcsec
    Transient Offset Posterior: 9.9647e-01
2026-10-14 11:25:53,641- INFO -

Properties of 2nd best host (in decals dr9) for 2025nxh:
    Redshift: 0.2541 ± 0.0583 (PHOT)
    Absolute Magnitude: -20.1 ± 1.0 (r)
    Transient Offset: 286.0 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:25:53,642- INFO - Chosen galaxy has catalog ID of 9906618674450204 and RA, DEC = 314.822865, -7.433470
2026-10-14 11:25:53,652- INFO - Conditioning association on the following properties: ['offset']

48/127 done: 2025nxh

2026-10-14 11:25:55,654- INFO - Loaded GLADE+ catalog.
2026-10-14 11:25:55,656- INFO -

Associating 2026pab at RA, DEC = 252.723100, -15.005308 (redshift nan)
2026-10-14 11:25:56,086- INFO - Running with shred_cut = True...
2026-10-14 11:26:02,512- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:26:02,755- INFO - Removed 9 flagged panstarrs sources.
2026-10-14 11:26:02,833- INFO - Association successful!
2026-10-14 11:26:02,861- INFO -

Properties of best host (in panstarrs dr2) for 2026pab:
    objID: 89992527227655664
    R.A. (deg): 252.722732
    Dec. (deg): -15.003968
    Posterior: 9.9087e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 5.0 ± 0.1 arcsec
    Transient Offset Posterior: 9.9087e-01
2026-10-14 11:26:02,861- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026pab:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 208.2 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:26:02,862- INFO - Chosen galaxy has catalog ID of 89992527227655664 and RA, DEC = 252.722732, -15.003968
2026-10-14 11:26:02,873- INFO - Conditioning association on the following properties: ['offset']

49/127 done: 2026pab

2026-10-14 11:26:05,016- INFO - Loaded GLADE+ catalog.
2026-10-14 11:26:05,018- INFO -

Associating 2026nul at RA, DEC = 339.949478, -14.597685 (redshift nan)
2026-10-14 11:26:05,670- WARNING - Association failed. Host is likely outside the search cone.
2026-10-14 11:26:05,673- INFO - Running with shred_cut = True...
2026-10-14 11:26:09,132- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:26:09,188- INFO - Removed 2 flagged panstarrs sources.
2026-10-14 11:26:09,211- INFO - Association successful!
2026-10-14 11:26:09,220- INFO -

Properties of best host (in panstarrs dr2) for 2026nul:
    objID: 90483399473693788
    R.A. (deg): 339.947362
    Dec. (deg): -14.597192
    Posterior: 9.9960e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 7.6 ± 0.1 arcsec
    Transient Offset Posterior: 9.9960e-01
2026-10-14 11:26:09,220- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026nul:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 128.2 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:26:09,221- INFO - Chosen galaxy has catalog ID of 90483399473693788 and RA, DEC = 339.947362, -14.597192
2026-10-14 11:26:09,239- INFO - Conditioning association on the following properties: ['offset']

50/127 done: 2026nul

2026-10-14 11:26:11,219- INFO - Loaded GLADE+ catalog.
2026-10-14 11:26:11,220- INFO -

Associating 2025qqr at RA, DEC = 341.880977, -8.515254 (redshift nan)
2026-10-14 11:26:12,731- INFO - Association successful!
2026-10-14 11:26:12,748- INFO -

Properties of best host (in decals dr9) for 2025qqr:
    objID: 9906618307183713
    R.A. (deg): 341.880561
    Dec. (deg): -8.515732
    Posterior: 9.9984e-01
    Redshift: 0.0629 ± 0.0031 (SPEC)
    Absolute Magnitude: -20.9 ± 0.8 (r)
    Transient Offset: 2.3 ± 0.1 arcsec
    Transient Offset Posterior: 9.9984e-01
2026-10-14 11:26:12,748- INFO -

Properties of 2nd best host (in decals dr9) for 2025qqr:
    Redshift: 0.5210 ± 0.1324 (PHOT)
    Absolute Magnitude: -19.8 ± 1.1 (r)
    Transient Offset: 283.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:26:12,748- INFO - Chosen galaxy has catalog ID of 9906618307183713 and RA, DEC = 341.880561, -8.515732
2026-10-14 11:26:12,758- INFO - Conditioning association on the following properties: ['offset']

51/127 done: 2025qqr

2026-10-14 11:26:14,656- INFO - Loaded GLADE+ catalog.
2026-10-14 11:26:14,657- INFO -

Associating 2026kxa at RA, DEC = 339.813537, -12.753700 (redshift nan)
2026-10-14 11:26:16,342- INFO - Association successful!
2026-10-14 11:26:16,365- INFO -

Properties of best host (in decals dr9) for 2026kxa:
    objID: 9906616727962684
    R.A. (deg): 339.818720
    Dec. (deg): -12.755916
    Posterior: 1.0000e+00
    Redshift: 0.0914 ± 0.0192 (PHOT)
    Absolute Magnitude: -19.7 ± 0.9 (r)
    Transient Offset: 19.9 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:26:16,365- INFO -

Properties of 2nd best host (in decals dr9) for 2026kxa:
    Redshift: 0.9692 ± 0.4846 (PHOT)
    Absolute Magnitude: -20.5 ± 1.2 (r)
    Transient Offset: 293.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:26:16,365- INFO - Chosen galaxy has catalog ID of 9906616727962684 and RA, DEC = 339.818720, -12.755916
2026-10-14 11:26:16,375- INFO - Conditioning association on the following properties: ['offset']

52/127 done: 2026kxa

2026-10-14 11:26:18,259- INFO - Loaded GLADE+ catalog.
2026-10-14 11:26:18,260- INFO -

Associating 2025qqj at RA, DEC = 332.134380, -16.148319 (redshift nan)
2026-10-14 11:26:18,634- INFO - Running with shred_cut = True...
2026-10-14 11:26:21,560- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:26:21,613- INFO - Removed 1 flagged panstarrs sources.
2026-10-14 11:26:21,635- INFO - Association successful!
2026-10-14 11:26:21,642- INFO -

Properties of best host (in panstarrs dr2) for 2025qqj:
    objID: 88623321342932520
    R.A. (deg): 332.134304
    Dec. (deg): -16.148079
    Posterior: 9.9997e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 0.9 ± 0.1 arcsec
    Transient Offset Posterior: 9.9997e-01
2026-10-14 11:26:21,643- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2025qqj:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 149.7 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:26:21,643- INFO - Chosen galaxy has catalog ID of 88623321342932520 and RA, DEC = 332.134304, -16.148079
2026-10-14 11:26:21,653- INFO - Conditioning association on the following properties: ['offset']

53/127 done: 2025qqj

2026-10-14 11:26:23,663- INFO - Loaded GLADE+ catalog.
2026-10-14 11:26:23,666- INFO -

Associating 2026qfd at RA, DEC = 329.932687, -20.022331 (redshift nan)
2026-10-14 11:26:24,087- INFO - Running with shred_cut = True...
2026-10-14 11:26:32,350- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:26:32,711- INFO - Removed 3 flagged panstarrs sources.
2026-10-14 11:26:33,210- INFO - Association successful!
2026-10-14 11:26:33,246- INFO -

Properties of best host (in panstarrs dr2) for 2026qfd:
    objID: 83973299324263533
    R.A. (deg): 329.932419
    Dec. (deg): -20.022284
    Posterior: 9.9733e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 0.9 ± 0.1 arcsec
    Transient Offset Posterior: 9.9733e-01
2026-10-14 11:26:33,249- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026qfd:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 191.4 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:26:33,256- INFO - Chosen galaxy has catalog ID of 83973299324263533 and RA, DEC = 329.932419, -20.022284
2026-10-14 11:26:33,315- INFO - Conditioning association on the following properties: ['offset']

54/127 done: 2026qfd

2026-10-14 11:26:39,548- INFO - Loaded GLADE+ catalog.
2026-10-14 11:26:39,556- INFO -

Associating 2026ohw at RA, DEC = 337.159481, 0.265872 (redshift nan)
2026-10-14 11:26:42,852- INFO - Association successful!
2026-10-14 11:26:42,907- INFO -

Properties of best host (in decals dr9) for 2026ohw:
    objID: 9906621599979274
    R.A. (deg): 337.159279
    Dec. (deg): 0.266123
    Posterior: 9.9920e-01
    Redshift: 0.0585 ± 0.0029 (SPEC)
    Absolute Magnitude: -21.0 ± 0.8 (r)
    Transient Offset: 1.2 ± 0.1 arcsec
    Transient Offset Posterior: 9.9920e-01
2026-10-14 11:26:42,907- INFO -

Properties of 2nd best host (in decals dr9) for 2026ohw:
    Redshift: 1.2246 ± 0.6105 (PHOT)
    Absolute Magnitude: -20.1 ± 1.2 (r)
    Transient Offset: 299.3 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:26:42,908- INFO - Chosen galaxy has catalog ID of 9906621599979274 and RA, DEC = 337.159279, 0.266123
2026-10-14 11:26:42,940- INFO - Conditioning association on the following properties: ['offset']

55/127 done: 2026ohw

2026-10-14 11:26:46,778- INFO - Loaded GLADE+ catalog.
2026-10-14 11:26:46,784- INFO -

Associating 2025jzl at RA, DEC = 330.901473, -11.841026 (redshift nan)
2026-10-14 11:26:48,470- INFO - Association successful!
2026-10-14 11:26:48,486- INFO -

Properties of best host (in decals dr9) for 2025jzl:
    objID: 9906617095098876
    R.A. (deg): 330.901510
    Dec. (deg): -11.841118
    Posterior: 1.0000e+00
    Redshift: 0.0571 ± 0.0198 (PHOT)
    Absolute Magnitude: -19.8 ± 0.9 (r)
    Transient Offset: 0.4 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:26:48,487- INFO -

Properties of 2nd best host (in decals dr9) for 2025jzl:
    Redshift: 0.4242 ± 0.0366 (PHOT)
    Absolute Magnitude: -21.8 ± 1.0 (r)
    Transient Offset: 293.2 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:26:48,487- INFO - Chosen galaxy has catalog ID of 9906617095098876 and RA, DEC = 330.901510, -11.841118
2026-10-14 11:26:48,501- INFO - Conditioning association on the following properties: ['offset']

56/127 done: 2025jzl

2026-10-14 11:26:50,501- INFO - Loaded GLADE+ catalog.
2026-10-14 11:26:50,502- INFO -

Associating 2026qiz at RA, DEC = 325.579412, -12.795119 (redshift nan)
2026-10-14 11:26:52,172- INFO - Association successful!
2026-10-14 11:26:52,189- INFO -

Properties of best host (in decals dr9) for 2026qiz:
    objID: 9906616724294504
    R.A. (deg): 325.578811
    Dec. (deg): -12.795553
    Posterior: 1.0000e+00
    Redshift: 0.1326 ± 0.0411 (PHOT)
    Absolute Magnitude: -19.3 ± 1.0 (r)
    Transient Offset: 2.6 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:26:52,190- INFO -

Properties of 2nd best host (in decals dr9) for 2026qiz:
    Redshift: 0.8881 ± 0.2760 (PHOT)
    Absolute Magnitude: -21.3 ± 1.1 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:26:52,190- INFO - Chosen galaxy has catalog ID of 9906616724294504 and RA, DEC = 325.578811, -12.795553
2026-10-14 11:26:52,202- INFO - Conditioning association on the following properties: ['offset']

57/127 done: 2026qiz

2026-10-14 11:26:54,306- INFO - Loaded GLADE+ catalog.
2026-10-14 11:26:54,310- INFO -

Associating 2025lwt at RA, DEC = 327.623195, -13.655640 (redshift nan)
2026-10-14 11:26:56,510- INFO - Association successful!
2026-10-14 11:26:56,538- INFO -

Properties of best host (in decals dr9) for 2025lwt:
    objID: 9906616356831908
    R.A. (deg): 327.623075
    Dec. (deg): -13.655839
    Posterior: 1.0000e+00
    Redshift: 0.2283 ± 0.1142 (PHOT)
    Absolute Magnitude: -18.4 ± 1.1 (r)
    Transient Offset: 0.8 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:26:56,538- INFO -

Properties of 2nd best host (in decals dr9) for 2025lwt:
    objID: 9906616356832012
    R.A. (deg): 327.627165
    Dec. (deg): -13.716451
    Posterior: 0.0000e+00
    Redshift: 0.5588 ± 0.0583 (PHOT)
    Absolute Magnitude: -21.5 ± 1.1 (r)
    Transient Offset: 219.4 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:26:56,538- INFO - Chosen galaxy has catalog ID of 9906616356831908 and RA, DEC = 327.623075, -13.655839
2026-10-14 11:26:56,551- INFO - Conditioning association on the following properties: ['offset']

58/127 done: 2025lwt

2026-10-14 11:26:58,507- INFO - Loaded GLADE+ catalog.
2026-10-14 11:26:58,509- INFO -

Associating 2025mzr at RA, DEC = 325.332858, -18.077863 (redshift nan)
2026-10-14 11:26:58,996- INFO - Running with shred_cut = True...
2026-10-14 11:27:02,547- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:27:02,608- INFO - Removed 1 flagged panstarrs sources.
2026-10-14 11:27:02,633- INFO - Association successful!
2026-10-14 11:27:02,641- INFO -

Properties of best host (in panstarrs dr2) for 2025mzr:
    objID: 86303253354528149
    R.A. (deg): 325.335485
    Dec. (deg): -18.076864
    Posterior: 7.9446e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 9.7 ± 0.1 arcsec
    Transient Offset Posterior: 7.9446e-01
2026-10-14 11:27:02,642- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2025mzr:
    objID: 86303253287929530
    R.A. (deg): 325.328804
    Dec. (deg): -18.075703
    Posterior: 2.0286e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 15.9 ± 0.1 arcsec
    Transient Offset Posterior: 2.0286e-01
2026-10-14 11:27:02,642- INFO - Chosen galaxy has catalog ID of 86303253354528149 and RA, DEC = 325.335485, -18.076864
2026-10-14 11:27:02,675- INFO - Conditioning association on the following properties: ['offset']

59/127 done: 2025mzr

2026-10-14 11:27:04,723- INFO - Loaded GLADE+ catalog.
2026-10-14 11:27:04,725- INFO -

Associating 2025rku at RA, DEC = 332.375696, -19.186636 (redshift nan)
2026-10-14 11:27:05,240- INFO - Running with shred_cut = True...
2026-10-14 11:27:09,491- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:27:09,543- INFO - No panstarrs shreds found.
2026-10-14 11:27:09,563- INFO - Association successful!
2026-10-14 11:27:09,570- INFO -

Properties of best host (in panstarrs dr2) for 2025rku:
    objID: 84973323753046466
    R.A. (deg): 332.375295
    Dec. (deg): -19.186670
    Posterior: 9.9844e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 9.9844e-01
2026-10-14 11:27:09,570- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2025rku:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 227.8 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:27:09,571- INFO - Chosen galaxy has catalog ID of 84973323753046466 and RA, DEC = 332.375295, -19.186670
2026-10-14 11:27:09,580- INFO - Conditioning association on the following properties: ['offset']

60/127 done: 2025rku

2026-10-14 11:27:11,558- INFO - Loaded GLADE+ catalog.
2026-10-14 11:27:11,559- INFO -

Associating 2025ows at RA, DEC = 332.544319, -7.650034 (redshift nan)
2026-10-14 11:27:13,573- INFO - Association successful!
2026-10-14 11:27:13,599- INFO -

Properties of best host (in decals dr9) for 2025ows:
    objID: 9906618585383614
    R.A. (deg): 332.543907
    Dec. (deg): -7.650211
    Posterior: 1.0000e+00
    Redshift: 0.0423 ± 0.0211 (PHOT)
    Absolute Magnitude: -17.8 ± 0.9 (r)
    Transient Offset: 1.6 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:27:13,599- INFO -

Properties of 2nd best host (in decals dr9) for 2025ows:
    Redshift: 0.9455 ± 0.1363 (PHOT)
    Absolute Magnitude: -21.0 ± 1.1 (r)
    Transient Offset: 293.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:27:13,599- INFO - Chosen galaxy has catalog ID of 9906618585383614 and RA, DEC = 332.543907, -7.650211
2026-10-14 11:27:13,612- INFO - Conditioning association on the following properties: ['offset']

61/127 done: 2025ows

2026-10-14 11:27:15,687- INFO - Loaded GLADE+ catalog.
2026-10-14 11:27:15,689- INFO -

Associating 2025txu at RA, DEC = 329.879261, -8.183509 (redshift nan)
2026-10-14 11:27:17,466- INFO - Association successful!
2026-10-14 11:27:17,485- INFO -

Properties of best host (in decals dr9) for 2025txu:
    objID: 9906618397495156
    R.A. (deg): 329.879433
    Dec. (deg): -8.183587
    Posterior: 1.0000e+00
    Redshift: 0.1329 ± 0.0665 (PHOT)
    Absolute Magnitude: -18.6 ± 1.0 (r)
    Transient Offset: 0.7 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:27:17,486- INFO -

Properties of 2nd best host (in decals dr9) for 2025txu:
    Redshift: 1.0176 ± 0.1718 (PHOT)
    Absolute Magnitude: -21.4 ± 1.1 (r)
    Transient Offset: 277.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:27:17,486- INFO - Chosen galaxy has catalog ID of 9906618397495156 and RA, DEC = 329.879433, -8.183587
2026-10-14 11:27:17,498- INFO - Conditioning association on the following properties: ['offset']

62/127 done: 2025txu

2026-10-14 11:27:19,417- INFO - Loaded GLADE+ catalog.
2026-10-14 11:27:19,419- INFO -

Associating 2026nrq at RA, DEC = 325.601587, -20.352575 (redshift nan)
2026-10-14 11:27:19,918- INFO - Running with shred_cut = True...
2026-10-14 11:27:23,867- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:27:23,934- INFO - Removed 1 flagged panstarrs sources.
2026-10-14 11:27:23,961- INFO - Association successful!
2026-10-14 11:27:23,970- INFO -

Properties of best host (in panstarrs dr2) for 2026nrq:
    objID: 83573256016767157
    R.A. (deg): 325.601685
    Dec. (deg): -20.352510
    Posterior: 8.8532e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 0.4 ± 0.1 arcsec
    Transient Offset Posterior: 8.8532e-01
2026-10-14 11:27:23,971- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026nrq:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 210.0 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:27:23,971- INFO - Chosen galaxy has catalog ID of 83573256016767157 and RA, DEC = 325.601685, -20.352510
2026-10-14 11:27:23,982- INFO - Conditioning association on the following properties: ['offset']

63/127 done: 2026nrq

2026-10-14 11:27:25,911- INFO - Loaded GLADE+ catalog.
2026-10-14 11:27:25,912- INFO -

Associating 2026qrh at RA, DEC = 64.185342, -48.943229 (redshift nan)
2026-10-14 11:27:28,437- INFO - Association successful!
2026-10-14 11:27:28,475- INFO -

Properties of best host (in decals dr9) for 2026qrh:
    objID: 9906605092569380
    R.A. (deg): 64.185370
    Dec. (deg): -48.943233
    Posterior: 9.8808e-01
    Redshift: 0.1125 ± 0.0167 (PHOT)
    Absolute Magnitude: -20.9 ± 0.9 (r)
    Transient Offset: 0.1 ± 0.1 arcsec
    Transient Offset Posterior: 9.8808e-01
2026-10-14 11:27:28,476- INFO -

Properties of 2nd best host (in decals dr9) for 2026qrh:
    Redshift: 1.2030 ± 0.1423 (PHOT)
    Absolute Magnitude: -21.5 ± 1.2 (r)
    Transient Offset: 297.7 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:27:28,476- INFO - Chosen galaxy has catalog ID of 9906605092569380 and RA, DEC = 64.185370, -48.943233
2026-10-14 11:27:28,486- INFO - Conditioning association on the following properties: ['offset']

64/127 done: 2026qrh

2026-10-14 11:27:30,432- INFO - Loaded GLADE+ catalog.
2026-10-14 11:27:30,433- INFO -

Associating 2025qio at RA, DEC = 309.046576, -15.865488 (redshift nan)
2026-10-14 11:27:31,337- INFO - Running with shred_cut = True...
2026-10-14 11:27:35,871- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:27:36,011- INFO - Removed 1 flagged panstarrs sources.
2026-10-14 11:27:36,066- INFO - Association successful!
2026-10-14 11:27:36,085- INFO -

Properties of best host (in panstarrs dr2) for 2025qio:
    objID: 88963090480520395
    R.A. (deg): 309.048058
    Dec. (deg): -15.866700
    Posterior: 7.0421e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 6.7 ± 0.1 arcsec
    Transient Offset Posterior: 7.0421e-01
2026-10-14 11:27:36,086- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2025qio:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 83.0 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:27:36,086- INFO - Chosen galaxy has catalog ID of 88963090480520395 and RA, DEC = 309.048058, -15.866700
2026-10-14 11:27:36,097- INFO - Conditioning association on the following properties: ['offset']

65/127 done: 2025qio

2026-10-14 11:27:38,246- INFO - Loaded GLADE+ catalog.
2026-10-14 11:27:38,249- INFO -

Associating 2026qdd at RA, DEC = 312.374902, -18.730331 (redshift nan)
2026-10-14 11:27:38,806- INFO - Running with shred_cut = True...
2026-10-14 11:27:44,139- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:27:44,259- INFO - Removed 6 flagged panstarrs sources.
2026-10-14 11:27:44,308- INFO - Association successful!
2026-10-14 11:27:44,323- INFO -

Properties of best host (in panstarrs dr2) for 2026qdd:
    objID: 85523123766592898
    R.A. (deg): 312.376652
    Dec. (deg): -18.731239
    Posterior: 9.9221e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 6.8 ± 0.1 arcsec
    Transient Offset Posterior: 9.9221e-01
2026-10-14 11:27:44,324- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026qdd:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 231.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:27:44,324- INFO - Chosen galaxy has catalog ID of 85523123766592898 and RA, DEC = 312.376652, -18.731239
2026-10-14 11:27:44,337- INFO - Conditioning association on the following properties: ['offset']

66/127 done: 2026qdd

2026-10-14 11:27:46,736- INFO - Loaded GLADE+ catalog.
2026-10-14 11:27:46,741- INFO -

Associating 2026nfu at RA, DEC = 298.816591, -12.217870 (redshift nan)
2026-10-14 11:27:47,192- INFO - Running with shred_cut = True...
2026-10-14 11:27:53,317- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:27:53,599- INFO - Removed 7 flagged panstarrs sources.
2026-10-14 11:27:53,681- INFO - Association successful!
2026-10-14 11:27:53,711- INFO -

Properties of best host (in panstarrs dr2) for 2026nfu:
    objID: 93332988162549492
    R.A. (deg): 298.816231
    Dec. (deg): -12.217439
    Posterior: 9.9740e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 2.0 ± 0.1 arcsec
    Transient Offset Posterior: 9.9740e-01
2026-10-14 11:27:53,711- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026nfu:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:27:53,712- INFO - Chosen galaxy has catalog ID of 93332988162549492 and RA, DEC = 298.816231, -12.217439
2026-10-14 11:27:53,723- INFO - Conditioning association on the following properties: ['offset']

67/127 done: 2026nfu

2026-10-14 11:27:57,706- INFO - Loaded GLADE+ catalog.
2026-10-14 11:27:57,712- INFO -

Associating 2026qbn at RA, DEC = 301.112057, -13.009268 (redshift nan)
2026-10-14 11:27:58,188- INFO - Running with shred_cut = True...
2026-10-14 11:28:06,894- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:28:07,090- INFO - Removed 4 flagged panstarrs sources.
2026-10-14 11:28:07,157- INFO - Association successful!
2026-10-14 11:28:07,180- INFO -

Properties of best host (in panstarrs dr2) for 2026qbn:
    objID: 92383011141189083
    R.A. (deg): 301.114121
    Dec. (deg): -13.009437
    Posterior: 8.1481e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 7.3 ± 0.1 arcsec
    Transient Offset Posterior: 8.1481e-01
2026-10-14 11:28:07,180- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026qbn:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 228.9 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:28:07,180- INFO - Chosen galaxy has catalog ID of 92383011141189083 and RA, DEC = 301.114121, -13.009437
2026-10-14 11:28:07,216- INFO - Conditioning association on the following properties: ['offset']

68/127 done: 2026qbn

2026-10-14 11:28:09,525- INFO - Loaded GLADE+ catalog.
2026-10-14 11:28:09,527- INFO -

Associating 2026hlr at RA, DEC = 312.027272, -12.846440 (redshift nan)
2026-10-14 11:28:10,067- INFO - Running with shred_cut = True...
2026-10-14 11:28:15,100- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:28:15,227- INFO - Removed 1 flagged panstarrs sources.
2026-10-14 11:28:15,276- INFO - Association successful!
2026-10-14 11:28:15,296- INFO -

Properties of best host (in panstarrs dr2) for 2026hlr:
    objID: 92583120271914306
    R.A. (deg): 312.027231
    Dec. (deg): -12.846732
    Posterior: 9.9002e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 1.1 ± 0.1 arcsec
    Transient Offset Posterior: 9.9002e-01
2026-10-14 11:28:15,297- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026hlr:
    objID: 92573119764323553
    R.A. (deg): 311.976434
    Dec. (deg): -12.855774
    Posterior: 0.0000e+00
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 181.6 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:28:15,297- INFO - Chosen galaxy has catalog ID of 92583120271914306 and RA, DEC = 312.027231, -12.846732
2026-10-14 11:28:15,335- INFO - Conditioning association on the following properties: ['offset']

69/127 done: 2026hlr

2026-10-14 11:28:17,706- INFO - Loaded GLADE+ catalog.
2026-10-14 11:28:17,708- INFO -

Associating 2025pie at RA, DEC = 311.032119, -18.056293 (redshift nan)
2026-10-14 11:28:18,224- INFO - Running with shred_cut = True...
2026-10-14 11:28:32,290- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:28:32,426- INFO - Removed 6 flagged panstarrs sources.
2026-10-14 11:28:32,480- INFO - Association successful!
2026-10-14 11:28:32,497- INFO -

Properties of best host (in panstarrs dr2) for 2025pie:
    objID: 86333110311322323
    R.A. (deg): 311.031150
    Dec. (deg): -18.056687
    Posterior: 9.7666e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 3.6 ± 0.1 arcsec
    Transient Offset Posterior: 9.7666e-01
2026-10-14 11:28:32,497- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2025pie:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 52.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:28:32,498- INFO - Chosen galaxy has catalog ID of 86333110311322323 and RA, DEC = 311.031150, -18.056687
2026-10-14 11:28:32,513- INFO - Conditioning association on the following properties: ['offset']

70/127 done: 2025pie

2026-10-14 11:28:34,844- INFO - Loaded GLADE+ catalog.
2026-10-14 11:28:34,846- INFO -

Associating 2025lxh at RA, DEC = 304.195195, -22.289518 (redshift nan)
2026-10-14 11:28:35,413- INFO - Running with shred_cut = True...
2026-10-14 11:28:40,018- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:28:40,155- INFO - Removed 2 flagged panstarrs sources.
2026-10-14 11:28:40,206- INFO - Association successful!
2026-10-14 11:28:40,224- INFO -

Properties of best host (in panstarrs dr2) for 2025lxh:
    objID: 81253041950412888
    R.A. (deg): 304.195039
    Dec. (deg): -22.289524
    Posterior: 9.5913e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 0.5 ± 0.1 arcsec
    Transient Offset Posterior: 9.5913e-01
2026-10-14 11:28:40,225- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2025lxh:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 31.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:28:40,225- INFO - Chosen galaxy has catalog ID of 81253041950412888 and RA, DEC = 304.195039, -22.289524
2026-10-14 11:28:40,234- INFO - Conditioning association on the following properties: ['offset']

71/127 done: 2025lxh

2026-10-14 11:28:43,165- INFO - Loaded GLADE+ catalog.
2026-10-14 11:28:43,182- INFO -

Associating 2026llc at RA, DEC = 309.294988, -26.191632 (redshift nan)
2026-10-14 11:28:43,810- INFO - Running with shred_cut = True...
2026-10-14 11:28:57,763- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:28:57,872- INFO - Removed 1 flagged panstarrs sources.
2026-10-14 11:28:57,918- INFO - Association successful!
2026-10-14 11:28:57,935- INFO -

Properties of best host (in panstarrs dr2) for 2026llc:
    objID: 76573092956620015
    R.A. (deg): 309.295657
    Dec. (deg): -26.191900
    Posterior: 1.0000e+00
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 2.4 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:28:57,935- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026llc:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 266.9 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:28:57,937- INFO - Chosen galaxy has catalog ID of 76573092956620015 and RA, DEC = 309.295657, -26.191900
2026-10-14 11:28:57,951- INFO - Conditioning association on the following properties: ['offset']

72/127 done: 2026llc

2026-10-14 11:29:00,062- INFO - Loaded GLADE+ catalog.
2026-10-14 11:29:00,064- INFO -

Associating 2026mzl at RA, DEC = 308.763827, -21.804600 (redshift nan)
2026-10-14 11:29:00,606- INFO - Running with shred_cut = True...
2026-10-14 11:29:05,654- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:29:05,809- INFO - Removed 2 flagged panstarrs sources.
2026-10-14 11:29:05,871- INFO - Association successful!
2026-10-14 11:29:05,891- INFO -

Properties of best host (in panstarrs dr2) for 2026mzl:
    objID: 81833087667865828
    R.A. (deg): 308.766928
    Dec. (deg): -21.803765
    Posterior: 4.4967e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 10.8 ± 0.1 arcsec
    Transient Offset Posterior: 4.4967e-01
2026-10-14 11:29:05,891- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2026mzl:
    objID: 81833087647491813
    R.A. (deg): 308.764811
    Dec. (deg): -21.807075
    Posterior: 2.9839e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 9.5 ± 0.1 arcsec
    Transient Offset Posterior: 2.9839e-01
2026-10-14 11:29:05,891- INFO - Chosen galaxy has catalog ID of 81833087667865828 and RA, DEC = 308.766928, -21.803765
2026-10-14 11:29:05,903- INFO - Conditioning association on the following properties: ['offset']

73/127 done: 2026mzl

2026-10-14 11:29:08,056- INFO - Loaded GLADE+ catalog.
2026-10-14 11:29:08,058- INFO -

Associating 2025imw at RA, DEC = 310.178614, -20.435643 (redshift nan)
2026-10-14 11:29:08,802- INFO - Running with shred_cut = True...
2026-10-14 11:29:14,852- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:29:14,986- INFO - Removed 23 flagged panstarrs sources.
2026-10-14 11:29:15,037- INFO - Association successful!
2026-10-14 11:29:15,054- INFO -

Properties of best host (in panstarrs dr2) for 2025imw:
    objID: 83473101780730914
    R.A. (deg): 310.178090
    Dec. (deg): -20.441226
    Posterior: 4.3221e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 20.2 ± 0.1 arcsec
    Transient Offset Posterior: 4.3221e-01
2026-10-14 11:29:15,055- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2025imw:
    objID: 83473101799986384
    R.A. (deg): 310.180010
    Dec. (deg): -20.436668
    Posterior: 3.4737e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 6.0 ± 0.1 arcsec
    Transient Offset Posterior: 3.4737e-01
2026-10-14 11:29:15,055- INFO - Chosen galaxy has catalog ID of 83473101780730914 and RA, DEC = 310.178090, -20.441226
2026-10-14 11:29:15,072- INFO - Conditioning association on the following properties: ['offset']

74/127 done: 2025imw

2026-10-14 11:29:17,289- INFO - Loaded GLADE+ catalog.
2026-10-14 11:29:17,291- INFO -

Associating 2025qaz at RA, DEC = 312.613622, -23.346686 (redshift nan)
2026-10-14 11:29:17,878- INFO - Running with shred_cut = True...
2026-10-14 11:29:21,664- INFO - Removing panstarrs dr2 shreds.
2026-10-14 11:29:21,785- INFO - Removed 1 flagged panstarrs sources.
2026-10-14 11:29:21,825- INFO - Association successful!
2026-10-14 11:29:21,840- INFO -

Properties of best host (in panstarrs dr2) for 2025qaz:
    objID: 79983126136483689
    R.A. (deg): 312.613616
    Dec. (deg): -23.347225
    Posterior: 9.9976e-01
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 1.9 ± 0.1 arcsec
    Transient Offset Posterior: 9.9976e-01
2026-10-14 11:29:21,840- INFO -

Properties of 2nd best host (in panstarrs dr2) for 2025qaz:
    Redshift: 0.0000 ± 0.0000
    Absolute Magnitude: 0.0 ± 0.0
    Transient Offset: 177.9 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:29:21,841- INFO - Chosen galaxy has catalog ID of 79983126136483689 and RA, DEC = 312.613616, -23.347225
2026-10-14 11:29:21,857- INFO - Conditioning association on the following properties: ['offset']

75/127 done: 2025qaz

2026-10-14 11:29:25,282- INFO - Loaded GLADE+ catalog.
2026-10-14 11:29:25,297- INFO -

Associating 2026onr at RA, DEC = 314.997109, -22.430263 (redshift nan)
2026-10-14 11:29:26,037- INFO - Running with shred_cut = True...

In [ ]:
results