In [1]:
import pandas as pd
from pathlib import Path

In [2]:
transients = pd.read_parquet(
    "snia_results.parquet",
    engine="fastparquet",
)

In [3]:
transients

,diaObjectId,tns_name,z,catalogue_object_id,tns_prefix,type,ra,decl,absMag,nDiaSources
0,170019717277810735,2026ctw,0.150000,"10000,342494,11570",SN,SN Ia,151.740293,1.927064,NaN,754
1,170028486191218743,2026qrh,0.100000,"10000,81273,866",SN,SN Ia,64.185342,-48.943229,NaN,88
2,170028500610711681,2024xom,0.044167,CGCG036-024,SN,SN Ia,150.746125,2.336469,NaN,165
3,170028510695916335,2025mbp,0.046160,2MASXJ10062208+0109317,SN,SN Ia,151.592617,1.158385,NaN,273
4,170028520834072659,2026fgl,0.164000,WISEAJ095652.35+032811.7,SN,SN Ia,149.218165,3.469919,-16.5385,19
...,...,...,...,...,...,...,...,...,...,...
122,170661828398940941,2025bbx,0.067000,14470795-3930390,SN,SN Ia,221.785403,-39.509297,NaN,3
123,313893021499785278,2026ezw,0.131000,SDSSJ095832.59+011610.2,SN,SN Ia,149.635687,1.269344,NaN,20
124,313932566867476549,2026qrh,0.100000,"10000,81273,866",SN,SN Ia,64.185342,-48.943229,NaN,9
125,313972182793322538,2026fgl,0.164000,WISEAJ095652.35+032811.7,SN,SN Ia,149.218165,3.469919,-16.2020,17
126,313976545586708672,2026fgl,0.164000,2MASXJ09565234+0328119,SN,SN Ia,149.218165,3.469919,-17.2440,146

In [4]:
transients = (
    transients[["diaObjectId", "tns_name", "ra", "decl"]]
    .rename(columns={"decl": "dec"})
    .dropna()
    .reset_index(drop=True)
    .copy()
)

transients["tns_name"] = transients["tns_name"].astype(str)

print(f"Associating {len(transients)} transients")
display(transients)

Associating 127 transients

            diaObjectId tns_name          ra        dec
0    170019717277810735  2026ctw  151.740293   1.927064
1    170028486191218743  2026qrh   64.185342 -48.943229
2    170028500610711681  2024xom  150.746125   2.336469
3    170028510695916335  2025mbp  151.592617   1.158385
4    170028520834072659  2026fgl  149.218165   3.469919
..                  ...      ...         ...        ...
122  170661828398940941  2025bbx  221.785403 -39.509297
123  313893021499785278  2026ezw  149.635687   1.269344
124  313932566867476549  2026qrh   64.185342 -48.943229
125  313972182793322538  2026fgl  149.218165   3.469919
126  313976545586708672  2026fgl  149.218165   3.469919

[127 rows x 4 columns]

In [ ]:
import inspect
import textwrap
import traceback

import pandas as pd
import astro_prost.helpers as prost_helpers
from scipy.stats import gamma, uniform
from astro_prost import associate_sample

# Temporary read-only fix without editing helpers.py.
if not getattr(prost_helpers, "_shape_r_copy_patch_applied", False):
    source = textwrap.dedent(
        inspect.getsource(prost_helpers.calc_shape_props_decals)
    )

    old = 'candidate_hosts["shape_r"].values'
    new = 'candidate_hosts["shape_r"].to_numpy(copy=True)'

    if old not in source:
        raise RuntimeError("Expected shape_r code not found.")

    source = source.replace(old, new)
    exec(
        compile(source, "<prost_notebook_patch>", "exec"),
        prost_helpers.__dict__,
    )
    prost_helpers._shape_r_copy_patch_applied = True

# Collect results in memory.
results = []
failed = []

for i in range(len(transients)):
    one_transient = transients.iloc[[i]].copy().reset_index(drop=True)
    name = str(one_transient.iloc[0]["tns_name"])

    try:
        result = associate_sample(
        one_transient,
        catalogs=["decals", "panstarrs", "skymapper"],
        name_col="tns_name",
        coord_cols=("ra", "dec"),
        priors={"offset": uniform(loc=0, scale=10)},
        likes={"offset": gamma(a=0.75)},
        n_samples=1000,  # Match the 1,000 samples used internally.
        parallel=False,
        save=False,
        )
    

        if isinstance(result, Exception):
            raise result

        if not isinstance(result, pd.DataFrame):
            raise TypeError(
                f"Expected DataFrame; got {type(result).__name__}"
            )

        if result.empty:
            raise ValueError("PROST returned an empty DataFrame.")

        results.append(result)
        print(f"{i + 1}/{len(transients)} done: {name}")

    except Exception as exc:
        failed.append({"tns_name": name, "error": repr(exc)})
        print(f"{i + 1}/{len(transients)} failed: {name}: {exc}")
        traceback.print_exc()

hosts = pd.concat(results, ignore_index=True) if results else pd.DataFrame()
failed_df = pd.DataFrame(failed, columns=["tns_name", "error"])

display(hosts)
display(failed_df)

2026-10-14 11:11:42,749- INFO - Conditioning association on the following properties: ['offset']
2026-10-14 11:11:44,913- INFO - Loaded GLADE+ catalog.
2026-10-14 11:11:44,916- INFO -

Associating 2026ctw at RA, DEC = 151.740293, 1.927064 (redshift nan)
2026-10-14 11:11:47,741- INFO - Association successful!
2026-10-14 11:11:47,760- INFO -

Properties of best host (in decals dr9) for 2026ctw:
    objID: 9906622211952776
    R.A. (deg): 151.740166
    Dec. (deg): 1.927030
    Posterior: 1.0000e+00
    Redshift: 0.7213 ± 0.3376 (PHOT)
    Absolute Magnitude: -20.3 ± 1.1 (r)
    Transient Offset: 0.5 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:11:47,760- INFO -

Properties of 2nd best host (in decals dr9) for 2026ctw:
    Redshift: 1.0042 ± 0.1648 (PHOT)
    Absolute Magnitude: -19.8 ± 1.2 (r)
    Transient Offset: 292.4 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:11:47,761- INFO - Chosen galaxy has catalog ID of 9906622211952776 and RA, DEC = 151.740166, 1.927030
2026-10-14 11:11:47,771- INFO - Conditioning association on the following properties: ['offset']

1/127 done: 2026ctw

2026-10-14 11:11:49,748- INFO - Loaded GLADE+ catalog.
2026-10-14 11:11:49,750- INFO -

Associating 2026qrh at RA, DEC = 64.185342, -48.943229 (redshift nan)
2026-10-14 11:11:52,642- INFO - Association successful!
2026-10-14 11:11:52,685- INFO -

Properties of best host (in decals dr9) for 2026qrh:
    objID: 9906605092569380
    R.A. (deg): 64.185370
    Dec. (deg): -48.943233
    Posterior: 9.8797e-01
    Redshift: 0.1125 ± 0.0167 (PHOT)
    Absolute Magnitude: -20.9 ± 0.9 (r)
    Transient Offset: 0.1 ± 0.1 arcsec
    Transient Offset Posterior: 9.8797e-01
2026-10-14 11:11:52,686- INFO -

Properties of 2nd best host (in decals dr9) for 2026qrh:
    Redshift: 1.2030 ± 0.1423 (PHOT)
    Absolute Magnitude: -21.5 ± 1.2 (r)
    Transient Offset: 297.7 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:11:52,686- INFO - Chosen galaxy has catalog ID of 9906605092569380 and RA, DEC = 64.185370, -48.943233
2026-10-14 11:11:52,697- INFO - Conditioning association on the following properties: ['offset']

2/127 done: 2026qrh

2026-10-14 11:11:54,657- INFO - Loaded GLADE+ catalog.
2026-10-14 11:11:54,659- INFO -

Associating 2024xom at RA, DEC = 150.746125, 2.336469 (redshift nan)
2026-10-14 11:11:56,601- INFO - Association successful!
2026-10-14 11:11:56,626- INFO -

Properties of best host (in decals dr9) for 2024xom:
    objID: 9906622306063947
    R.A. (deg): 150.743722
    Dec. (deg): 2.335828
    Posterior: 7.3390e-01
    Redshift: 0.1483 ± 0.0741 (PHOT)
    Absolute Magnitude: -20.1 ± 1.0 (r)
    Transient Offset: 8.9 ± 0.1 arcsec
    Transient Offset Posterior: 7.3390e-01
2026-10-14 11:11:56,627- INFO -

Properties of 2nd best host (in decals dr9) for 2024xom:
    Redshift: 0.7043 ± 0.3117 (PHOT)
    Absolute Magnitude: -19.5 ± 1.2 (r)
    Transient Offset: 299.4 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:11:56,627- INFO - Chosen galaxy has catalog ID of 9906622306063947 and RA, DEC = 150.743722, 2.335828
2026-10-14 11:11:56,639- INFO - Conditioning association on the following properties: ['offset']

3/127 done: 2024xom

2026-10-14 11:11:58,526- INFO - Loaded GLADE+ catalog.
2026-10-14 11:11:58,527- INFO -

Associating 2025mbp at RA, DEC = 151.592617, 1.158385 (redshift nan)
2026-10-14 11:12:00,827- INFO - Association successful!
2026-10-14 11:12:00,847- INFO -

Properties of best host (in decals dr9) for 2025mbp:
    objID: 9906621928834589
    R.A. (deg): 151.591936
    Dec. (deg): 1.159004
    Posterior: 1.0000e+00
    Redshift: 0.0462 ± 0.0023 (SPEC)
    Absolute Magnitude: -19.3 ± 0.9 (r)
    Transient Offset: 3.3 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:12:00,847- INFO -

Properties of 2nd best host (in decals dr9) for 2025mbp:
    Redshift: 0.4413 ± 0.1184 (PHOT)
    Absolute Magnitude: -19.1 ± 1.1 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:00,847- INFO - Chosen galaxy has catalog ID of 9906621928834589 and RA, DEC = 151.591936, 1.159004
2026-10-14 11:12:00,859- INFO - Conditioning association on the following properties: ['offset']

4/127 done: 2025mbp

2026-10-14 11:12:02,800- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:02,802- INFO -

Associating 2026fgl at RA, DEC = 149.218165, 3.469919 (redshift nan)
2026-10-14 11:12:08,403- INFO - Association successful!
2026-10-14 11:12:08,420- INFO -

Properties of best host (in decals dr9) for 2026fgl:
    objID: 9906622777393393
    R.A. (deg): 149.218121
    Dec. (deg): 3.469923
    Posterior: 1.0000e+00
    Redshift: 0.1643 ± 0.0082 (SPEC)
    Absolute Magnitude: -22.3 ± 0.9 (r)
    Transient Offset: 0.2 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:12:08,421- INFO -

Properties of 2nd best host (in decals dr9) for 2026fgl:
    Redshift: 0.9634 ± 0.1610 (PHOT)
    Absolute Magnitude: -20.6 ± 1.2 (r)
    Transient Offset: 297.4 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:08,421- INFO - Chosen galaxy has catalog ID of 9906622777393393 and RA, DEC = 149.218121, 3.469923
2026-10-14 11:12:08,432- INFO - Conditioning association on the following properties: ['offset']

5/127 done: 2026fgl

2026-10-14 11:12:10,695- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:10,698- INFO -

Associating 2026fgt at RA, DEC = 186.188879, 6.589125 (redshift nan)
2026-10-14 11:12:12,524- INFO - Association successful!
2026-10-14 11:12:12,547- INFO -

Properties of best host (in decals dr9) for 2026fgt:
    objID: 9906623916018877
    R.A. (deg): 186.189092
    Dec. (deg): 6.589056
    Posterior: 1.0000e+00
    Redshift: 0.5220 ± 0.1206 (PHOT)
    Absolute Magnitude: -19.9 ± 1.1 (r)
    Transient Offset: 0.8 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:12:12,548- INFO -

Properties of 2nd best host (in decals dr9) for 2026fgt:
    Redshift: 0.2019 ± 0.0239 (PHOT)
    Absolute Magnitude: -21.8 ± 0.9 (r)
    Transient Offset: 299.2 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:12,548- INFO - Chosen galaxy has catalog ID of 9906623916018877 and RA, DEC = 186.189092, 6.589056
2026-10-14 11:12:12,560- INFO - Conditioning association on the following properties: ['offset']

6/127 done: 2026fgt

2026-10-14 11:12:14,597- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:14,599- INFO -

Associating 2026ewl at RA, DEC = 185.547821, 7.747500 (redshift nan)
2026-10-14 11:12:16,862- INFO - Association successful!
2026-10-14 11:12:16,893- INFO -

Properties of best host (in decals dr9) for 2026ewl:
    objID: 9906624384598107
    R.A. (deg): 185.547957
    Dec. (deg): 7.746464
    Posterior: 1.0000e+00
    Redshift: 0.1355 ± 0.0068 (SPEC)
    Absolute Magnitude: -22.5 ± 0.8 (r)
    Transient Offset: 3.8 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:12:16,893- INFO -

Properties of 2nd best host (in decals dr9) for 2026ewl:
    Redshift: 0.9054 ± 0.2016 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 298.3 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:16,893- INFO - Chosen galaxy has catalog ID of 9906624384598107 and RA, DEC = 185.547957, 7.746464
2026-10-14 11:12:16,903- INFO - Conditioning association on the following properties: ['offset']

7/127 done: 2026ewl

2026-10-14 11:12:18,810- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:18,811- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:12:21,049- INFO - Association successful!
2026-10-14 11:12:21,079- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9075e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9075e-01
2026-10-14 11:12:21,080- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:21,080- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:12:21,093- INFO - Conditioning association on the following properties: ['offset']

8/127 done: 2024bhx

2026-10-14 11:12:23,102- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:23,104- INFO -

Associating 2024adyk at RA, DEC = 186.016373, 8.411760 (redshift nan)
2026-10-14 11:12:24,801- INFO - Association successful!
2026-10-14 11:12:24,823- INFO -

Properties of best host (in decals dr9) for 2024adyk:
    objID: 9906624665227522
    R.A. (deg): 186.015520
    Dec. (deg): 8.410711
    Posterior: 7.3235e-01
    Redshift: 0.0771 ± 0.0039 (SPEC)
    Absolute Magnitude: -21.5 ± 0.8 (r)
    Transient Offset: 4.8 ± 0.1 arcsec
    Transient Offset Posterior: 7.3235e-01
2026-10-14 11:12:24,823- INFO -

Properties of 2nd best host (in decals dr9) for 2024adyk:
    Redshift: 0.8190 ± 0.1135 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:24,823- INFO - Chosen galaxy has catalog ID of 9906624665227522 and RA, DEC = 186.015520, 8.410711
2026-10-14 11:12:24,834- INFO - Conditioning association on the following properties: ['offset']

9/127 done: 2024adyk

2026-10-14 11:12:26,890- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:26,892- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:12:29,010- INFO - Association successful!
2026-10-14 11:12:29,040- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9387e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9387e-01
2026-10-14 11:12:29,041- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:29,041- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:12:29,052- INFO - Conditioning association on the following properties: ['offset']

10/127 done: 2024bhx

2026-10-14 11:12:31,072- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:31,074- INFO -

Associating 2024lah at RA, DEC = 185.996538, 7.725874 (redshift nan)
2026-10-14 11:12:33,223- INFO - Association successful!
2026-10-14 11:12:33,254- INFO -

Properties of best host (in decals dr9) for 2024lah:
    objID: 9906624384668493
    R.A. (deg): 185.996418
    Dec. (deg): 7.725895
    Posterior: 1.0000e+00
    Redshift: 0.0684 ± 0.0215 (PHOT)
    Absolute Magnitude: -19.4 ± 0.9 (r)
    Transient Offset: 0.4 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:12:33,254- INFO -

Properties of 2nd best host (in decals dr9) for 2024lah:
    Redshift: 1.1880 ± 0.3335 (PHOT)
    Absolute Magnitude: -20.1 ± 1.2 (r)
    Transient Offset: 296.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:33,254- INFO - Chosen galaxy has catalog ID of 9906624384668493 and RA, DEC = 185.996418, 7.725895
2026-10-14 11:12:33,299- INFO - Conditioning association on the following properties: ['offset']

11/127 done: 2024lah

2026-10-14 11:12:35,245- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:35,246- INFO -

Associating 2021hiz at RA, DEC = 186.423625, 7.228389 (redshift nan)
2026-10-14 11:12:37,105- INFO - Association successful!
2026-10-14 11:12:37,131- INFO -

Properties of best host (in decals dr9) for 2021hiz:
    objID: 9906624197430225
    R.A. (deg): 186.423926
    Dec. (deg): 7.226417
    Posterior: 8.4009e-01
    Redshift: 0.0364 ± 0.0182 (PHOT)
    Absolute Magnitude: -19.3 ± 0.8 (r)
    Transient Offset: 7.2 ± 0.1 arcsec
    Transient Offset Posterior: 8.4009e-01
2026-10-14 11:12:37,131- INFO -

Properties of 2nd best host (in decals dr9) for 2021hiz:
    Redshift: 1.2025 ± 0.5618 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:37,132- INFO - Chosen galaxy has catalog ID of 9906624197430225 and RA, DEC = 186.423926, 7.226417
2026-10-14 11:12:37,141- INFO - Conditioning association on the following properties: ['offset']

12/127 done: 2021hiz

2026-10-14 11:12:39,013- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:39,014- INFO -

Associating 2021ita at RA, DEC = 186.495177, 7.235433 (redshift nan)
2026-10-14 11:12:40,933- INFO - Association successful!
2026-10-14 11:12:40,958- INFO -

Properties of best host (in decals dr9) for 2021ita:
    objID: 9906624197431893
    R.A. (deg): 186.495065
    Dec. (deg): 7.235318
    Posterior: 9.9405e-01
    Redshift: 0.1510 ± 0.0188 (PHOT)
    Absolute Magnitude: -21.5 ± 0.9 (r)
    Transient Offset: 0.6 ± 0.1 arcsec
    Transient Offset Posterior: 9.9405e-01
2026-10-14 11:12:40,959- INFO -

Properties of 2nd best host (in decals dr9) for 2021ita:
    Redshift: 0.6744 ± 0.1422 (PHOT)
    Absolute Magnitude: -20.4 ± 1.1 (r)
    Transient Offset: 296.7 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:40,959- INFO - Chosen galaxy has catalog ID of 9906624197431893 and RA, DEC = 186.495065, 7.235318
2026-10-14 11:12:40,969- INFO - Conditioning association on the following properties: ['offset']

13/127 done: 2021ita

2026-10-14 11:12:43,048- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:43,049- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:12:45,862- INFO - Association successful!
2026-10-14 11:12:45,892- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.8973e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.8973e-01
2026-10-14 11:12:45,893- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:45,893- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:12:45,903- INFO - Conditioning association on the following properties: ['offset']

14/127 done: 2024bhx

2026-10-14 11:12:47,864- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:47,866- INFO -

Associating 2024lah at RA, DEC = 185.996538, 7.725874 (redshift nan)
2026-10-14 11:12:50,207- INFO - Association successful!
2026-10-14 11:12:50,238- INFO -

Properties of best host (in decals dr9) for 2024lah:
    objID: 9906624384668493
    R.A. (deg): 185.996418
    Dec. (deg): 7.725895
    Posterior: 1.0000e+00
    Redshift: 0.0684 ± 0.0215 (PHOT)
    Absolute Magnitude: -19.4 ± 0.9 (r)
    Transient Offset: 0.4 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:12:50,238- INFO -

Properties of 2nd best host (in decals dr9) for 2024lah:
    Redshift: 1.1880 ± 0.3335 (PHOT)
    Absolute Magnitude: -20.1 ± 1.2 (r)
    Transient Offset: 296.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:50,239- INFO - Chosen galaxy has catalog ID of 9906624384668493 and RA, DEC = 185.996418, 7.725895
2026-10-14 11:12:50,249- INFO - Conditioning association on the following properties: ['offset']

15/127 done: 2024lah

2026-10-14 11:12:52,200- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:52,202- INFO -

Associating 2024adyk at RA, DEC = 186.016373, 8.411760 (redshift nan)
2026-10-14 11:12:53,790- INFO - Association successful!
2026-10-14 11:12:53,811- INFO -

Properties of best host (in decals dr9) for 2024adyk:
    objID: 9906624665227522
    R.A. (deg): 186.015520
    Dec. (deg): 8.410711
    Posterior: 7.3198e-01
    Redshift: 0.0771 ± 0.0039 (SPEC)
    Absolute Magnitude: -21.5 ± 0.8 (r)
    Transient Offset: 4.8 ± 0.1 arcsec
    Transient Offset Posterior: 7.3198e-01
2026-10-14 11:12:53,811- INFO -

Properties of 2nd best host (in decals dr9) for 2024adyk:
    Redshift: 0.8190 ± 0.1135 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:53,811- INFO - Chosen galaxy has catalog ID of 9906624665227522 and RA, DEC = 186.015520, 8.410711
2026-10-14 11:12:53,822- INFO - Conditioning association on the following properties: ['offset']

16/127 done: 2024adyk

2026-10-14 11:12:55,792- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:55,793- INFO -

Associating 2021hiz at RA, DEC = 186.423625, 7.228389 (redshift nan)
2026-10-14 11:12:57,977- INFO - Association successful!
2026-10-14 11:12:58,013- INFO -

Properties of best host (in decals dr9) for 2021hiz:
    objID: 9906624197430225
    R.A. (deg): 186.423926
    Dec. (deg): 7.226417
    Posterior: 8.4047e-01
    Redshift: 0.0364 ± 0.0182 (PHOT)
    Absolute Magnitude: -19.3 ± 0.8 (r)
    Transient Offset: 7.2 ± 0.1 arcsec
    Transient Offset Posterior: 8.4047e-01
2026-10-14 11:12:58,014- INFO -

Properties of 2nd best host (in decals dr9) for 2021hiz:
    Redshift: 1.2025 ± 0.5618 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:12:58,014- INFO - Chosen galaxy has catalog ID of 9906624197430225 and RA, DEC = 186.423926, 7.226417
2026-10-14 11:12:58,025- INFO - Conditioning association on the following properties: ['offset']

17/127 done: 2021hiz

2026-10-14 11:12:59,995- INFO - Loaded GLADE+ catalog.
2026-10-14 11:12:59,996- INFO -

Associating 2021hiz at RA, DEC = 186.423625, 7.228389 (redshift nan)
2026-10-14 11:13:01,848- INFO - Association successful!
2026-10-14 11:13:01,874- INFO -

Properties of best host (in decals dr9) for 2021hiz:
    objID: 9906624197430225
    R.A. (deg): 186.423926
    Dec. (deg): 7.226417
    Posterior: 8.3970e-01
    Redshift: 0.0364 ± 0.0182 (PHOT)
    Absolute Magnitude: -19.3 ± 0.8 (r)
    Transient Offset: 7.2 ± 0.1 arcsec
    Transient Offset Posterior: 8.3970e-01
2026-10-14 11:13:01,874- INFO -

Properties of 2nd best host (in decals dr9) for 2021hiz:
    Redshift: 1.2025 ± 0.5618 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:01,875- INFO - Chosen galaxy has catalog ID of 9906624197430225 and RA, DEC = 186.423926, 7.226417
2026-10-14 11:13:01,892- INFO - Conditioning association on the following properties: ['offset']

18/127 done: 2021hiz

2026-10-14 11:13:03,786- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:03,788- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:13:05,826- INFO - Association successful!
2026-10-14 11:13:05,858- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9226e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9226e-01
2026-10-14 11:13:05,859- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:05,859- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:13:05,870- INFO - Conditioning association on the following properties: ['offset']

19/127 done: 2024bhx

2026-10-14 11:13:07,975- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:07,979- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:13:10,252- INFO - Association successful!
2026-10-14 11:13:10,283- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9417e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9417e-01
2026-10-14 11:13:10,284- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:10,284- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:13:10,341- INFO - Conditioning association on the following properties: ['offset']

20/127 done: 2024bhx

2026-10-14 11:13:12,350- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:12,351- INFO -

Associating 2024lah at RA, DEC = 185.996538, 7.725874 (redshift nan)
2026-10-14 11:13:14,692- INFO - Association successful!
2026-10-14 11:13:14,804- INFO -

Properties of best host (in decals dr9) for 2024lah:
    objID: 9906624384668493
    R.A. (deg): 185.996418
    Dec. (deg): 7.725895
    Posterior: 1.0000e+00
    Redshift: 0.0684 ± 0.0215 (PHOT)
    Absolute Magnitude: -19.4 ± 0.9 (r)
    Transient Offset: 0.4 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:13:14,805- INFO -

Properties of 2nd best host (in decals dr9) for 2024lah:
    Redshift: 1.1880 ± 0.3335 (PHOT)
    Absolute Magnitude: -20.1 ± 1.2 (r)
    Transient Offset: 296.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:14,805- INFO - Chosen galaxy has catalog ID of 9906624384668493 and RA, DEC = 185.996418, 7.725895
2026-10-14 11:13:14,819- INFO - Conditioning association on the following properties: ['offset']

21/127 done: 2024lah

2026-10-14 11:13:18,462- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:18,469- INFO -

Associating 2021ita at RA, DEC = 186.495177, 7.235433 (redshift nan)
2026-10-14 11:13:20,271- INFO - Association successful!
2026-10-14 11:13:20,298- INFO -

Properties of best host (in decals dr9) for 2021ita:
    objID: 9906624197431893
    R.A. (deg): 186.495065
    Dec. (deg): 7.235318
    Posterior: 9.9414e-01
    Redshift: 0.1510 ± 0.0188 (PHOT)
    Absolute Magnitude: -21.5 ± 0.9 (r)
    Transient Offset: 0.6 ± 0.1 arcsec
    Transient Offset Posterior: 9.9414e-01
2026-10-14 11:13:20,299- INFO -

Properties of 2nd best host (in decals dr9) for 2021ita:
    Redshift: 0.6744 ± 0.1422 (PHOT)
    Absolute Magnitude: -20.4 ± 1.1 (r)
    Transient Offset: 296.7 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:20,299- INFO - Chosen galaxy has catalog ID of 9906624197431893 and RA, DEC = 186.495065, 7.235318
2026-10-14 11:13:20,313- INFO - Conditioning association on the following properties: ['offset']

22/127 done: 2021ita

2026-10-14 11:13:22,543- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:22,545- INFO -

Associating 2024lah at RA, DEC = 185.996538, 7.725874 (redshift nan)
2026-10-14 11:13:24,716- INFO - Association successful!
2026-10-14 11:13:24,747- INFO -

Properties of best host (in decals dr9) for 2024lah:
    objID: 9906624384668493
    R.A. (deg): 185.996418
    Dec. (deg): 7.725895
    Posterior: 1.0000e+00
    Redshift: 0.0684 ± 0.0215 (PHOT)
    Absolute Magnitude: -19.4 ± 0.9 (r)
    Transient Offset: 0.4 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:13:24,748- INFO -

Properties of 2nd best host (in decals dr9) for 2024lah:
    Redshift: 1.1880 ± 0.3335 (PHOT)
    Absolute Magnitude: -20.1 ± 1.2 (r)
    Transient Offset: 296.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:24,748- INFO - Chosen galaxy has catalog ID of 9906624384668493 and RA, DEC = 185.996418, 7.725895
2026-10-14 11:13:24,759- INFO - Conditioning association on the following properties: ['offset']

23/127 done: 2024lah

2026-10-14 11:13:26,770- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:26,772- INFO -

Associating 2026ekf at RA, DEC = 187.707737, 8.273932 (redshift nan)
2026-10-14 11:13:28,453- INFO - Association successful!
2026-10-14 11:13:28,478- INFO -

Properties of best host (in decals dr9) for 2026ekf:
    objID: 9906624572230448
    R.A. (deg): 187.707788
    Dec. (deg): 8.273854
    Posterior: 9.9995e-01
    Redshift: 0.2933 ± 0.1099 (PHOT)
    Absolute Magnitude: -19.2 ± 1.1 (r)
    Transient Offset: 0.4 ± 0.1 arcsec
    Transient Offset Posterior: 9.9995e-01
2026-10-14 11:13:28,478- INFO -

Properties of 2nd best host (in decals dr9) for 2026ekf:
    Redshift: 0.3727 ± 0.1018 (PHOT)
    Absolute Magnitude: -19.5 ± 1.1 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:28,479- INFO - Chosen galaxy has catalog ID of 9906624572230448 and RA, DEC = 187.707788, 8.273854
2026-10-14 11:13:28,489- INFO - Conditioning association on the following properties: ['offset']

24/127 done: 2026ekf

2026-10-14 11:13:30,458- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:30,460- INFO -

Associating 2021hiz at RA, DEC = 186.423625, 7.228389 (redshift nan)
2026-10-14 11:13:32,583- INFO - Association successful!
2026-10-14 11:13:32,608- INFO -

Properties of best host (in decals dr9) for 2021hiz:
    objID: 9906624197430225
    R.A. (deg): 186.423926
    Dec. (deg): 7.226417
    Posterior: 8.4098e-01
    Redshift: 0.0364 ± 0.0182 (PHOT)
    Absolute Magnitude: -19.3 ± 0.8 (r)
    Transient Offset: 7.2 ± 0.1 arcsec
    Transient Offset Posterior: 8.4098e-01
2026-10-14 11:13:32,609- INFO -

Properties of 2nd best host (in decals dr9) for 2021hiz:
    Redshift: 1.2025 ± 0.5618 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:32,609- INFO - Chosen galaxy has catalog ID of 9906624197430225 and RA, DEC = 186.423926, 7.226417
2026-10-14 11:13:32,620- INFO - Conditioning association on the following properties: ['offset']

25/127 done: 2021hiz

2026-10-14 11:13:34,536- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:34,537- INFO -

Associating 2026kjm at RA, DEC = 186.147455, 7.728034 (redshift nan)
2026-10-14 11:13:36,571- INFO - Association successful!
2026-10-14 11:13:36,597- INFO -

Properties of best host (in decals dr9) for 2026kjm:
    objID: 9906624384731883
    R.A. (deg): 186.147688
    Dec. (deg): 7.727766
    Posterior: 1.0000e+00
    Redshift: 0.1004 ± 0.0194 (PHOT)
    Absolute Magnitude: -19.5 ± 0.9 (r)
    Transient Offset: 1.3 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:13:36,597- INFO -

Properties of 2nd best host (in decals dr9) for 2026kjm:
    Redshift: 1.0555 ± 0.4803 (PHOT)
    Absolute Magnitude: -20.8 ± 1.2 (r)
    Transient Offset: 293.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:36,597- INFO - Chosen galaxy has catalog ID of 9906624384731883 and RA, DEC = 186.147688, 7.727766
2026-10-14 11:13:36,607- INFO - Conditioning association on the following properties: ['offset']

26/127 done: 2026kjm

2026-10-14 11:13:38,607- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:38,608- INFO -

Associating 2021ita at RA, DEC = 186.495177, 7.235433 (redshift nan)
2026-10-14 11:13:40,490- INFO - Association successful!
2026-10-14 11:13:40,514- INFO -

Properties of best host (in decals dr9) for 2021ita:
    objID: 9906624197431893
    R.A. (deg): 186.495065
    Dec. (deg): 7.235318
    Posterior: 9.9405e-01
    Redshift: 0.1510 ± 0.0188 (PHOT)
    Absolute Magnitude: -21.5 ± 0.9 (r)
    Transient Offset: 0.6 ± 0.1 arcsec
    Transient Offset Posterior: 9.9405e-01
2026-10-14 11:13:40,515- INFO -

Properties of 2nd best host (in decals dr9) for 2021ita:
    Redshift: 0.6744 ± 0.1422 (PHOT)
    Absolute Magnitude: -20.4 ± 1.1 (r)
    Transient Offset: 296.7 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:40,515- INFO - Chosen galaxy has catalog ID of 9906624197431893 and RA, DEC = 186.495065, 7.235318
2026-10-14 11:13:40,525- INFO - Conditioning association on the following properties: ['offset']

27/127 done: 2021ita

2026-10-14 11:13:42,622- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:42,625- INFO -

Associating 2026kjm at RA, DEC = 186.147455, 7.728034 (redshift nan)
2026-10-14 11:13:44,456- INFO - Association successful!
2026-10-14 11:13:44,482- INFO -

Properties of best host (in decals dr9) for 2026kjm:
    objID: 9906624384731883
    R.A. (deg): 186.147688
    Dec. (deg): 7.727766
    Posterior: 1.0000e+00
    Redshift: 0.1004 ± 0.0194 (PHOT)
    Absolute Magnitude: -19.5 ± 0.9 (r)
    Transient Offset: 1.3 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:13:44,482- INFO -

Properties of 2nd best host (in decals dr9) for 2026kjm:
    Redshift: 1.0555 ± 0.4803 (PHOT)
    Absolute Magnitude: -20.8 ± 1.2 (r)
    Transient Offset: 293.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:44,483- INFO - Chosen galaxy has catalog ID of 9906624384731883 and RA, DEC = 186.147688, 7.727766
2026-10-14 11:13:44,493- INFO - Conditioning association on the following properties: ['offset']

28/127 done: 2026kjm

2026-10-14 11:13:46,493- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:46,495- INFO -

Associating 2021hiz at RA, DEC = 186.423625, 7.228389 (redshift nan)
2026-10-14 11:13:48,349- INFO - Association successful!
2026-10-14 11:13:48,375- INFO -

Properties of best host (in decals dr9) for 2021hiz:
    objID: 9906624197430225
    R.A. (deg): 186.423926
    Dec. (deg): 7.226417
    Posterior: 8.3925e-01
    Redshift: 0.0364 ± 0.0182 (PHOT)
    Absolute Magnitude: -19.3 ± 0.8 (r)
    Transient Offset: 7.2 ± 0.1 arcsec
    Transient Offset Posterior: 8.3925e-01
2026-10-14 11:13:48,375- INFO -

Properties of 2nd best host (in decals dr9) for 2021hiz:
    Redshift: 1.2025 ± 0.5618 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:48,375- INFO - Chosen galaxy has catalog ID of 9906624197430225 and RA, DEC = 186.423926, 7.226417
2026-10-14 11:13:48,387- INFO - Conditioning association on the following properties: ['offset']

29/127 done: 2021hiz

2026-10-14 11:13:50,379- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:50,381- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:13:52,380- INFO - Association successful!
2026-10-14 11:13:52,410- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9412e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9412e-01
2026-10-14 11:13:52,410- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:52,410- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:13:52,420- INFO - Conditioning association on the following properties: ['offset']

30/127 done: 2024bhx

2026-10-14 11:13:54,269- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:54,271- INFO -

Associating 2021hiz at RA, DEC = 186.423625, 7.228389 (redshift nan)
2026-10-14 11:13:56,082- INFO - Association successful!
2026-10-14 11:13:56,108- INFO -

Properties of best host (in decals dr9) for 2021hiz:
    objID: 9906624197430225
    R.A. (deg): 186.423926
    Dec. (deg): 7.226417
    Posterior: 8.3997e-01
    Redshift: 0.0364 ± 0.0182 (PHOT)
    Absolute Magnitude: -19.3 ± 0.8 (r)
    Transient Offset: 7.2 ± 0.1 arcsec
    Transient Offset Posterior: 8.3997e-01
2026-10-14 11:13:56,108- INFO -

Properties of 2nd best host (in decals dr9) for 2021hiz:
    Redshift: 1.2025 ± 0.5618 (PHOT)
    Absolute Magnitude: -20.4 ± 1.2 (r)
    Transient Offset: 294.1 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:13:56,108- INFO - Chosen galaxy has catalog ID of 9906624197430225 and RA, DEC = 186.423926, 7.226417
2026-10-14 11:13:56,118- INFO - Conditioning association on the following properties: ['offset']

31/127 done: 2021hiz

2026-10-14 11:13:58,161- INFO - Loaded GLADE+ catalog.
2026-10-14 11:13:58,162- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:14:00,358- INFO - Association successful!
2026-10-14 11:14:00,388- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9376e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9376e-01
2026-10-14 11:14:00,389- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:14:00,389- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:14:00,400- INFO - Conditioning association on the following properties: ['offset']

32/127 done: 2024bhx

2026-10-14 11:14:02,324- INFO - Loaded GLADE+ catalog.
2026-10-14 11:14:02,325- INFO -

Associating 2023dyl at RA, DEC = 150.744415, 2.343412 (redshift nan)
2026-10-14 11:14:04,102- INFO - Association successful!
2026-10-14 11:14:04,126- INFO -

Properties of best host (in decals dr9) for 2023dyl:
    objID: 9906622306063990
    R.A. (deg): 150.746064
    Dec. (deg): 2.343021
    Posterior: 8.4915e-01
    Redshift: 0.0328 ± 0.0065 (PHOT)
    Absolute Magnitude: -21.6 ± 0.7 (r)
    Transient Offset: 6.1 ± 0.1 arcsec
    Transient Offset Posterior: 8.4915e-01
2026-10-14 11:14:04,127- INFO -

Properties of 2nd best host (in decals dr9) for 2023dyl:
    Redshift: 0.6788 ± 0.2611 (PHOT)
    Absolute Magnitude: -19.8 ± 1.2 (r)
    Transient Offset: 294.0 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:14:04,127- INFO - Chosen galaxy has catalog ID of 9906622306063990 and RA, DEC = 150.746064, 2.343021
2026-10-14 11:14:04,137- INFO - Conditioning association on the following properties: ['offset']

33/127 done: 2023dyl

2026-10-14 11:14:06,118- INFO - Loaded GLADE+ catalog.
2026-10-14 11:14:06,120- INFO -

Associating 2024bhx at RA, DEC = 186.002957, 7.777518 (redshift nan)
2026-10-14 11:14:08,200- INFO - Association successful!
2026-10-14 11:14:08,230- INFO -

Properties of best host (in decals dr9) for 2024bhx:
    objID: 9906624384668666
    R.A. (deg): 186.002570
    Dec. (deg): 7.777459
    Posterior: 5.9339e-01
    Redshift: 0.0203 ± 0.0102 (PHOT)
    Absolute Magnitude: -16.0 ± 0.9 (r)
    Transient Offset: 1.4 ± 0.1 arcsec
    Transient Offset Posterior: 5.9339e-01
2026-10-14 11:14:08,231- INFO -

Properties of 2nd best host (in decals dr9) for 2024bhx:
    Redshift: 0.9056 ± 0.3533 (PHOT)
    Absolute Magnitude: -20.3 ± 1.2 (r)
    Transient Offset: 294.5 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:14:08,231- INFO - Chosen galaxy has catalog ID of 9906624384668666 and RA, DEC = 186.002570, 7.777459
2026-10-14 11:14:08,241- INFO - Conditioning association on the following properties: ['offset']

34/127 done: 2024bhx

2026-10-14 11:14:10,122- INFO - Loaded GLADE+ catalog.
2026-10-14 11:14:10,123- INFO -

Associating 2021ita at RA, DEC = 186.495177, 7.235433 (redshift nan)
2026-10-14 11:14:11,894- INFO - Association successful!
2026-10-14 11:14:11,919- INFO -

Properties of best host (in decals dr9) for 2021ita:
    objID: 9906624197431893
    R.A. (deg): 186.495065
    Dec. (deg): 7.235318
    Posterior: 9.9413e-01
    Redshift: 0.1510 ± 0.0188 (PHOT)
    Absolute Magnitude: -21.5 ± 0.9 (r)
    Transient Offset: 0.6 ± 0.1 arcsec
    Transient Offset Posterior: 9.9413e-01
2026-10-14 11:14:11,919- INFO -

Properties of 2nd best host (in decals dr9) for 2021ita:
    Redshift: 0.6744 ± 0.1422 (PHOT)
    Absolute Magnitude: -20.4 ± 1.1 (r)
    Transient Offset: 296.7 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:14:11,920- INFO - Chosen galaxy has catalog ID of 9906624197431893 and RA, DEC = 186.495065, 7.235318
2026-10-14 11:14:11,929- INFO - Conditioning association on the following properties: ['offset']

35/127 done: 2021ita

2026-10-14 11:14:13,911- INFO - Loaded GLADE+ catalog.
2026-10-14 11:14:13,913- INFO -

Associating 2026fgl at RA, DEC = 149.218165, 3.469919 (redshift nan)
2026-10-14 11:14:15,521- INFO - Association successful!
2026-10-14 11:14:15,539- INFO -

Properties of best host (in decals dr9) for 2026fgl:
    objID: 9906622777393393
    R.A. (deg): 149.218121
    Dec. (deg): 3.469923
    Posterior: 1.0000e+00
    Redshift: 0.1643 ± 0.0082 (SPEC)
    Absolute Magnitude: -22.3 ± 0.9 (r)
    Transient Offset: 0.2 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:14:15,539- INFO -

Properties of 2nd best host (in decals dr9) for 2026fgl:
    Redshift: 0.9634 ± 0.1610 (PHOT)
    Absolute Magnitude: -20.6 ± 1.2 (r)
    Transient Offset: 297.4 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:14:15,539- INFO - Chosen galaxy has catalog ID of 9906622777393393 and RA, DEC = 149.218121, 3.469923
2026-10-14 11:14:15,552- INFO - Conditioning association on the following properties: ['offset']

36/127 done: 2026fgl

2026-10-14 11:14:17,586- INFO - Loaded GLADE+ catalog.
2026-10-14 11:14:17,588- INFO -

Associating 2026fbm at RA, DEC = 150.032600, 3.024186 (redshift nan)
2026-10-14 11:14:19,970- INFO - Association successful!
2026-10-14 11:14:20,000- INFO -

Properties of best host (in decals dr9) for 2026fbm:
    objID: 9906622589043609
    R.A. (deg): 150.032161
    Dec. (deg): 3.024137
    Posterior: 1.0000e+00
    Redshift: 0.2602 ± 0.1301 (PHOT)
    Absolute Magnitude: -19.6 ± 1.1 (r)
    Transient Offset: 1.6 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:14:20,001- INFO -

Properties of 2nd best host (in decals dr9) for 2026fbm:
    Redshift: 1.0686 ± 0.5343 (PHOT)
    Absolute Magnitude: -20.2 ± 1.2 (r)
    Transient Offset: 299.6 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:14:20,001- INFO - Chosen galaxy has catalog ID of 9906622589043609 and RA, DEC = 150.032161, 3.024137
2026-10-14 11:14:20,011- INFO - Conditioning association on the following properties: ['offset']

37/127 done: 2026fbm

2026-10-14 11:14:22,058- INFO - Loaded GLADE+ catalog.
2026-10-14 11:14:22,059- INFO -

Associating 2026ezw at RA, DEC = 149.635687, 1.269344 (redshift nan)
2026-10-14 11:14:24,371- INFO - Association successful!
2026-10-14 11:14:24,396- INFO -

Properties of best host (in decals dr9) for 2026ezw:
    objID: 9906621928311970
    R.A. (deg): 149.635776
    Dec. (deg): 1.269511
    Posterior: 9.9993e-01
    Redshift: 0.1937 ± 0.0311 (PHOT)
    Absolute Magnitude: -21.3 ± 0.9 (r)
    Transient Offset: 0.7 ± 0.1 arcsec
    Transient Offset Posterior: 9.9993e-01
2026-10-14 11:14:24,397- INFO -

Properties of 2nd best host (in decals dr9) for 2026ezw:
    Redshift: 1.0017 ± 0.3546 (PHOT)
    Absolute Magnitude: -21.0 ± 1.2 (r)
    Transient Offset: 298.3 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:14:24,397- INFO - Chosen galaxy has catalog ID of 9906621928311970 and RA, DEC = 149.635776, 1.269511
2026-10-14 11:14:24,442- INFO - Conditioning association on the following properties: ['offset']

38/127 done: 2026ezw

2026-10-14 11:14:26,379- INFO - Loaded GLADE+ catalog.
2026-10-14 11:14:26,381- INFO -

Associating 2026ikn at RA, DEC = 149.943679, 3.780242 (redshift nan)
2026-10-14 11:14:29,540- INFO - Association successful!
2026-10-14 11:14:29,562- INFO -

Properties of best host (in decals dr9) for 2026ikn:
    objID: 9906622871769883
    R.A. (deg): 149.943689
    Dec. (deg): 3.780043
    Posterior: 1.0000e+00
    Redshift: 0.2276 ± 0.0430 (PHOT)
    Absolute Magnitude: -20.0 ± 1.0 (r)
    Transient Offset: 0.7 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:14:29,563- INFO -

Properties of 2nd best host (in decals dr9) for 2026ikn:
    Redshift: 0.8858 ± 0.4429 (PHOT)
    Absolute Magnitude: -20.7 ± 1.2 (r)
    Transient Offset: 295.2 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:14:29,563- INFO - Chosen galaxy has catalog ID of 9906622871769883 and RA, DEC = 149.943689, 3.780043
2026-10-14 11:14:29,573- INFO - Conditioning association on the following properties: ['offset']

39/127 done: 2026ikn

2026-10-14 11:14:31,482- INFO - Loaded GLADE+ catalog.
2026-10-14 11:14:31,483- INFO -

Associating 2026ftl at RA, DEC = 188.402327, 6.368380 (redshift nan)
2026-10-14 11:14:33,421- INFO - Association successful!
2026-10-14 11:14:33,443- INFO -

Properties of best host (in decals dr9) for 2026ftl:
    objID: 9906623822760158
    R.A. (deg): 188.402259
    Dec. (deg): 6.368652
    Posterior: 1.0000e+00
    Redshift: 0.3447 ± 0.1104 (PHOT)
    Absolute Magnitude: -20.0 ± 1.1 (r)
    Transient Offset: 1.0 ± 0.1 arcsec
    Transient Offset Posterior: 1.0000e+00
2026-10-14 11:14:33,444- INFO -

Properties of 2nd best host (in decals dr9) for 2026ftl:
    objID: 9906623822759252
    R.A. (deg): 188.356962
    Dec. (deg): 6.368931
    Posterior: 0.0000e+00
    Redshift: 0.7597 ± 0.1346 (PHOT)
    Absolute Magnitude: -20.4 ± 1.1 (r)
    Transient Offset: 162.3 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:14:33,444- INFO - Chosen galaxy has catalog ID of 9906623822760158 and RA, DEC = 188.402259, 6.368652
2026-10-14 11:14:33,454- INFO - Conditioning association on the following properties: ['offset']

40/127 done: 2026ftl

2026-10-14 11:14:35,767- INFO - Loaded GLADE+ catalog.
2026-10-14 11:14:35,788- INFO -

Associating 2026ivl at RA, DEC = 148.474283, 1.718233 (redshift nan)
2026-10-14 11:14:38,623- INFO - Association successful!
2026-10-14 11:14:38,654- INFO -

Properties of best host (in decals dr9) for 2026ivl:
    objID: 9906622116729406
    R.A. (deg): 148.474148
    Dec. (deg): 1.719041
    Posterior: 6.3173e-01
    Redshift: 0.1035 ± 0.0247 (PHOT)
    Absolute Magnitude: -19.3 ± 1.0 (r)
    Transient Offset: 3.0 ± 0.1 arcsec
    Transient Offset Posterior: 6.3173e-01
2026-10-14 11:14:38,654- INFO -

Properties of 2nd best host (in decals dr9) for 2026ivl:
    Redshift: 1.0438 ± 0.2868 (PHOT)
    Absolute Magnitude: -20.8 ± 1.2 (r)
    Transient Offset: 299.0 ± 0.1 arcsec
    Transient Offset Posterior: 0.0000e+00
2026-10-14 11:14:38,655- INFO - Chosen galaxy has catalog ID of 9906622116729406 and RA, DEC = 148.474148, 1.719041
2026-10-14 11:14:38,695- INFO - Conditioning association on the following properties: ['offset']

41/127 done: 2026ivl

2026-10-14 11:14:42,795- INFO - Loaded GLADE+ catalog.
2026-10-14 11:14:42,800- INFO -

Associating 2026kfw at RA, DEC = 149.219885, 1.833104 (redshift nan)
2026-10-14 11:14:45,030- WARNING - Association failed. Host is likely outside the search cone.
2026-10-14 11:14:45,063- INFO - Running with shred_cut = True...

In [ ]:
results